### ISSUE TITLE
Weather Controller disappears when inserting lilac

### ISSUE THREAD

**Issue by D1yt** [ProfElements/DynaTech#1]
## Description (Required)

Hey, when using the weather controller with a lilac, it just disappears instead of changing the weather. Sunflowers and creeper heads work just perfect.

## Steps to reproduce the Issue (Required)

-Get an energy setup (for example coal gen 2 and energy regulator)
-Place the weather controller
-Insert lilac into the slot in the middle

## Expected behavior (Required)

It should switch the weather to rain and not remove the machine ^^

## Server Log / Error Report

-Console log: https://pastebin.com/SvTeVT24
-Error file: https://pastebin.com/ahtJ2Hzi

## Environment (Required)

![image](https://user-images.githubusercontent.com/10422925/103172397-69d53d00-4853-11eb-8a59-123f2c35cd92.png)
![image](https://user-images.githubusercontent.com/10422925/103172402-76f22c00-4853-11eb-92e3-bfc4228760f4.png)
![image](https://user-images.githubusercontent.com/10422925/103172426-a3a64380-4853-11eb-82be-9216bdec2b8a.png)
![image](https://user-images.githubusercontent.com/10422925/103172432-ac971500-4853-11eb-8c40-48abc4636e1b.png)

 - Minecraft Version: 1.16.4
 - CS-CoreLib Version: DEV 92
 - Slimefun Version: DEV 769
 - Plugin Version: DEV 6

**Comment by ProfElements** [comment]
Just fixed. Thank you for the report :bow:
