### ISSUE TITLE
Infinite momentum of near-by entities with barbed_wire

### ISSUE THREAD

**Issue by SolaceAndKairos** [ProfElements/DynaTech#100]
Basic Information: Slimefun v4-DEV949, DynaTech DEV131, No CS-Corelib, MC v1.17.1, Spigot 3178... for 1.17.1
``/sf versions``
<img width="897" alt="1sfversions" src="https://user-images.githubusercontent.com/86926054/125350914-0c9f6580-e325-11eb-9f6f-32e1491f324a.png">

Discovery: One of the players on my server wanted to move mobs from a(n electric) spawner very fast so their limit of 6 nearby mobs would never be met.
They used barbed wire because it seemed very effective and cheap, and even now- I agree, VERY effective and extremely cheap / early game.
<img width="796" alt="2Setup" src="https://user-images.githubusercontent.com/86926054/125351749-15446b80-e326-11eb-845f-e34ae7ad4768.png">

Their set-up was ran overnight (afk is allowed on the server) and upon the morning, the server had strangely crashed.

World file (pruned to only include regions/poi starting with "4"): https://www.dropbox.com/sh/s4920ll11zily23/AAAv8bY2dCn6tPi50mKV6RdOa?dl=0
The problem: The barbed wire was actually TOO effective at moving entities away quickly.
The following crash reports resulted, but I'd like to note that the server crashed 10's of times while I tried to figure this out.

Crash Report 1: https://pastebin.com/yHV8FAac
Crash Report 2: https://pastebin.com/NzGhhtbP
Crash Report 3: https://pastebin.com/ibN9UbVs
Note: slimefun/error-reports remains empty.

I used the following guide for NBTExplorer to delete the chunk (-104,407) within region (-4,12), where the entities are located. 
https://gaming.stackexchange.com/questions/359445/how-do-i-delete-an-entity-from-the-minecraft-world-folder
![3ChunkDeleted](https://user-images.githubusercontent.com/86926054/125350919-0dd09280-e325-11eb-9c7a-9328bec20217.png)

This definitely removed the entity, but upon re-logging, new entities were simply created.
![4Reoccurance](https://user-images.githubusercontent.com/86926054/125350930-0f9a5600-e325-11eb-8be5-1d1119c8eccd.png)

I then removed both DynaTech and Electric Spawners and tried both of them individually.
When having DynaTech disabled and Elecctric Spawners enabled, the spawner behaved normally.
![5NormalSpawner](https://user-images.githubusercontent.com/86926054/125350900-090bde80-e325-11eb-8a75-28b45e6b0acd.png)
I then just removed the barbed wire before readding DynaTech to the server.

Currently, I am still using both plugins and all is working fine since I removed the barbed wire.
<img width="1920" alt="6AllGoodInParadise" src="https://user-images.githubusercontent.com/86926054/125350908-0b6e3880-e325-11eb-9b42-03874f681cfe.png">

**Comment by ProfElements** [comment]
I thought I capped the momentum 🙇 Will be fixed shortly
