### ISSUE TITLE
Culinary Generator not consuming the last tick of food

### ISSUE THREAD

**Issue by marvjosh1** [ProfElements/DynaTech#101]
## Description (Required)
Whenever you try to use the culinary generator, it will start working and generating energy from thee food, until the last tick where the food should fully be used. There, it gets stuck and completely stops working.

## Steps to reproduce the Issue (Required)
Step 1: Set up an energy network and place a culinary generator attached to it
Step 2: Place food in the culinary generator and wait until it gets to the last tick
https://youtu.be/1zIWDGlK_cE

## Expected behavior (Required)
The food gets consumed and the culinary generator starts consuming the next piece of food and continue producing energy.

## Server Log / Error Report
https://pastebin.com/AUnV2tS6

## Environment (Required)
https://i.imgur.com/n7uJtrS.png
https://i.imgur.com/aW2Q0px.png

**Comment by ProfElements** [comment]
Update to the latest DynaTech version.
