### ISSUE TITLE
Tesseracts throwing errors

### ISSUE THREAD

**Issue by marvjosh1** [ProfElements/DynaTech#102]
## Description (Required)
Tesseracts are throwing an error in console

## Steps to reproduce the Issue (Required)
Properly set up a tesseract and watch console
https://i.imgur.com/Di8arMu.jpeg

## Expected behavior (Required)
That tesseracts don't throw any errors in console

## Server Log / Error Report
https://pastebin.com/36h0uCqd

## Environment (Required)
https://i.imgur.com/n7uJtrS.png
https://i.imgur.com/aW2Q0px.png

**Comment by ProfElements** [comment]
Update to the latest DynaTech version.
