### ISSUE TITLE
Electrical Stimulator Fills your hunger bar when fully depleted.

### ISSUE THREAD

**Issue by Boomer-1** [ProfElements/DynaTech#103]
## Description (Required)

I crafted an electrical stimulator but did not charge it. I fell from about 15 blocks, enough to drain my hunger bar to repair my health. I was down 2 hunger hearts, then grabbed the stimulator. about 2 seconds later I was at full hunger.

## Steps to reproduce the Issue (Required)

https://youtu.be/fykGOeBf2Kw

## Expected behavior (Required)

to not fill my hunger bar when not charged.

## Server Log / Error Report

no errors

## Environment (Required)

 - Minecraft Version: 1.17.1
 - CS-CoreLib Version: n/a
 - Slimefun Version: 950
 - Plugin Version:  132

**Comment by ProfElements** [comment]
Fixed with f842cc0
