### ISSUE TITLE
so much lag

### ISSUE THREAD

**Issue by xsorencoolx** [ProfElements/DynaTech#104]
hello sir ive got so much weird lag on my server if you can help me with that
![Screenshot (110)](https://user-images.githubusercontent.com/51112473/128683555-be2f6d9a-a238-49bd-b23c-5d1c92970f91.png)
![Screenshot (111)](https://user-images.githubusercontent.com/51112473/128683562-e339f0ab-d7c8-448d-8b24-5a9dab8f2a6a.png)
![Screenshot (112)](https://user-images.githubusercontent.com/51112473/128683566-7cd4353e-dd6d-49df-be03-7fddf5e81f13.png)

**Comment by Seggan** [comment]
Please give a screenshot of `/sf versions`

**Comment by ProfElements** [comment]
If you havent already please update to the latest version. A contributor completely revamped `WATER_MILL`s to be much more efficient.

**Comment by ProfElements** [comment]
Any updates on this?
