### ISSUE TITLE
Chipping Generator not working with items with 0 durability

### ISSUE THREAD

**Issue by marvjosh1** [ProfElements/DynaTech#105]
## Description (Required)
Whenever a tool or armor with 0 durability is put in the chipping generator, it will not consume the tool and not work at all

## Steps to reproduce the Issue (Required)
Step 1: Set up a chipping generator connected to an energy network
Step 2: Put in a 0 durability item and watch it not get consumed and used
Step 3: If necessary, compare with a low durability item

## Expected behavior (Required)
The item to get consumed and produce a minor amount of energy

## Server Log / Error Report
none available

## Environment (Required)
https://i.imgur.com/pxrdrQ7.png
https://i.imgur.com/VQM4ADa.png

**Comment by ProfElements** [comment]
This is intended behavior. 0 durabilty items are not supposed to be consumed
