### ISSUE TITLE
[Angel Gem] - Flight Speed Modification

### ISSUE THREAD

**Issue by TheLittleCube** [ProfElements/DynaTech#106]
Requesting to add a configuration option to nerf the speed cap that is granted from using the gem.
That or just disable the speed boost completely. Creative flight is extremely overpowered... 
Let alone flying faster than chunks can load. 

Only other option I have is to Disabled the item completely via SF's own configuration.

**Comment by ProfElements** [comment]
There is already a max speed configuration found in Slimefun's Items.yml

**Comment by TheLittleCube** [comment]
> There is already a max speed configuration found in Slimefun's Items.yml

Thank you. Will change it there.
