### ISSUE TITLE
Material Hive Dupes Slimefun Items Incorrectly

### ISSUE THREAD

**Issue by Slimerson** [ProfElements/DynaTech#107]
The Material Hive seems to be having an issue when creating some Slimefun items. While I was looking into the machine I noticed that when it tries to create some Slimefun items, it creates a vanilla Minecraft item instead. I tried to use the machine to make Reinforced Alloy Ingots, but instead it created a vanilla Minecraft Iron Ingot.  I tested all of the slimefun resources, and the ones I experienced the bug with are below

-Reinforced Alloy Ingot
-Billion Ingot
-Hardened Metal 
-Damascus Steel Ingot
-Aluminum Brass Ingot
-Aluminum Bronze Ingot
-Corinthain Bronze Ingot
-Solder Ingot
-Ferrosilicon
- 24 - 4 Carat Gold 

Power up the Material Hive, put in any Slimefun item (For ex. Reinforced Alloy Ingot) wait for the machine to finish making the new item, and a vanilla Minecraft Item will be made. (In the video an Iron Ingot was created)
https://youtu.be/EfI3BbOWr64 

I expected when you put in a Slimefun item, the hive should create that Slimefun item instead of a Vanilla Minecraft item 

https://screenshots.skizzles.me/wAnA3/gaLokuBu84.png

**Comment by ProfElements** [comment]
i just tested with the latest version and this is not the case. Closing
