### ISSUE TITLE
chipping generator

### ISSUE THREAD

**Issue by RIPISDRAD** [ProfElements/DynaTech#121]
this is a bug when u put sth there and it's at full health It doesn't consume it!
it has to be damaged!
![2021-11-10_19 08 16](https://user-images.githubusercontent.com/76468672/141143940-0a6255e5-559c-4378-b60d-d4bdc19a6121.png)

**Comment by ProfElements** [comment]
This is intended so people don't just craft items to make insane bursts of power.
