### ISSUE TITLE
chipping gen bug

### ISSUE THREAD

**Issue by RIPISDRAD** [ProfElements/DynaTech#123]
when u put sth in it with full health it will not get consumed as u said
but if u put sf things it will consume them
I put an unbreakable thing from foxy + soulband  and it get consume
![2021-11-14_04 48 57](https://user-images.githubusercontent.com/76468672/141663985-357991da-94a4-4472-bd6f-461086599b4a.png)
d

**Comment by ProfElements** [comment]
Fixed with 4bd5aee
