### ISSUE TITLE
suggestion on wither skeletons

### ISSUE THREAD

**Issue by RIPISDRAD** [ProfElements/DynaTech#124]
CAN WE HAVE A CONFIG ON WITHERS?
so everyone can change its difficulty by their desire?

**Comment by ProfElements** [comment]
Please explain. I do not modify Withers at all within the addon. I do make a wither skeleton golem multiblock that can be completely disabled though.

**Comment by RIPISDRAD** [comment]
I want that ur wither golem be configure able cause every server economy is
different so people will need sth like this but not the way u imagined im
totally fine with this but a bit of configuration is needed for these
situations
