### ISSUE TITLE
Error on console on startup.

### ISSUE THREAD

**Issue by PhoenixCodingStuff** [ProfElements/DynaTech#131]
Description 
An error on console on startup.

Steps to reproduce the Issue
Add latest Slimefun4 (DEV 995) to your server and latest DynaTech (DEV 151).
Start the server.

Expected behavior
No error on console.

Server Log / Error Report
![unknown](https://user-images.githubusercontent.com/97077949/149662102-90d21b72-26a1-40a9-a9fc-38fe839c54d9.png)

Environment
 - Minecraft Version: 1.18.1
 - CS-CoreLib Version: N/A
 - Slimefun Version: DEV 995
 - Plugin Version: DEV 151
![unknown](https://user-images.githubusercontent.com/97077949/149662223-3254a6b6-9568-4c59-a9f2-bf86842254c8.png)
![unknown](https://user-images.githubusercontent.com/97077949/149662231-233f04ca-9cc6-47bc-9d91-6091974d8410.png)

**Comment by DexterSK** [comment]
same problem

**Comment by ProfElements** [comment]
This is just a warning you can ignore

**Comment by PhoenixCodingStuff** [comment]
okay

**Comment by ProfElements** [comment]
I can.
