### ISSUE TITLE
material hive not working

### ISSUE THREAD

**Issue by zwrumpy** [ProfElements/DynaTech#136]
## Description 
material hive not working

## Server Log / Error Report
screenshot -> https://prnt.sc/26laur4

## Environment 
Airplane paper 1.17.1
Slimefun RC - 30
DynaTech DEV - 158

**Comment by DexterSK** [comment]
yep same

**Comment by PhoenixCodingStuff** [comment]
I was just about to open an issue and found this

**Comment by ProfElements** [comment]
Fixed in 6ec8613
