### ISSUE TITLE
Liquid tank displaces water, does not add it to the tank and water does not flow back.

### ISSUE THREAD

**Issue by Boomer-1** [ProfElements/DynaTech#139]
## Description (Required)

When using a new liquid tank, when trying to pick up water it seems that only 1 bucket's worth will go into the tank, regardless of how many buckets are picked up. Additionally, at least visually water does not flow back after being picked up. While relogging into the server does show the water being replaced, it makes it very inconvenient to do so, and hard to work with the area if you don't.

## Steps to reproduce the Issue (Required)

https://user-images.githubusercontent.com/75179680/153718325-5ae7a552-27c3-4909-8ebf-c9beeb6d9cfd.mp4

## Expected behavior (Required)

the liquid tank to not leave holes in the water, and to pick up the water accounted for properly in the tank.

## Server Log / Error Report

no errors in console or slimefun error folder

## Environment (Required)

 - Minecraft Version: 1.18.1
 - CS-CoreLib Version: n/a
 - Slimefun Version: 999
 - Plugin Version: 160

**Comment by ProfElements** [comment]
Can you confirm this is still an issue?
