### ISSUE TITLE
Req: Option to limit flight speed with Gem

### ISSUE THREAD

**Issue by ZeeRaider** [ProfElements/DynaTech#14]
The current speed option of 3 chunks per second is likely okay if you run a server with world boarders and pre-gen but people being able to fly at such high speeds on an ungenerated world causes huge issues even on high end hardware.
If you could add a config option to limit the speed to 0.5 c/s - 1 c/s would be epic.

Many thanks for the consideration.

**Comment by ProfElements** [comment]
Resolved in 
6a4949e
