### ISSUE TITLE
Cannot open blocks that have inventories in dimensional home after server restarts

### ISSUE THREAD

**Issue by ybw0014** [ProfElements/DynaTech#140]
## Description (Required)

After restarting the server, the blocks that have inventories (like wireless item output that tested in vid, Tinker's Smeltery) in dimensional home cannot be open.
When using debug fish, the block has no inventory after server restarts.

## Steps to reproduce the Issue (Required)

https://youtu.be/6VNz2mevPyM
(this vid is a little bit long since I took a long time waiting for restarting)

1. Put an inventory block (wireless item output) in dimensional home.
2. Restart server
3. Right click the block, nothing happens.

## Expected behavior (Required)

Can open the block gui.

## Server Log / Error Report

N/A

## Environment (Required)

 - Minecraft Version: 1.18.1
 - CS-CoreLib Version:
 - Slimefun Version: 999
 - Plugin Version: 160

**Comment by ProfElements** [comment]
Can you confirm this is still an issue?

**Comment by Boomer-1** [comment]
can confirm. it happened to me as well

**Comment by ProfElements** [comment]
Fixed with the latest commit hopefully :crossed_fingers: Please confirm the fix once you get a chance to !
