### ISSUE TITLE
Portable Fluid Tank

### ISSUE THREAD

**Issue by WongIong** [ProfElements/DynaTech#141]
## Description (Required)
Players can fill the Tank by right click at water or lava that is not the source
In this case they can have unlimited Liquid

## Expected behavior (Required)
Only can filled by right click at source

## Server Log / Error Report
no error

## Environment (Required)
![image](https://user-images.githubusercontent.com/36799194/154724856-b36cf115-fdd0-4084-ad94-71570717ad1a.png)

**Comment by ProfElements** [comment]
This is intended currently as there is no way to properly mitigate it.
