### ISSUE TITLE
Hydra Generator reporting errors

### ISSUE THREAD

**Issue by hiphoprexx** [ProfElements/DynaTech#145]
## Description (Required)
The main problem is that the Hydra Generator and Hydra Turbines are throwing errors when trying to be used.
We connected a water source to the Hydra Turbines and put a Energy Regulator next to it but didn't generate any power.

## Steps to reproduce the Issue (Required)
connected a water source to the Hydra Turbines and put a Energy Regulator next to it but didn't generate any power.
![image](https://user-images.githubusercontent.com/44550623/165064182-841c031c-e4bf-4c68-bec8-30fd6b4c63df.png)

## Expected behavior (Required)
Generator Power lol

## Server Log / Error Report
DynaTech error report
https://pastebin.com/qWr4E7Fc
Server Log
https://pastebin.com/ThE45kMf

## Environment (Required)
![image](https://user-images.githubusercontent.com/44550623/165064862-87a08fd7-28c8-4d11-8aea-b69f0adec5b0.png)
![image](https://user-images.githubusercontent.com/44550623/165064877-98262275-de5b-4876-a9b7-f82377b4b5fd.png)

 - Minecraft Version: 1.18.2
 - CS-CoreLib Version: Not Used
 - Slimefun Version: Stable RC - 31 
 - Plugin Version: 163

Addictional:
Discord User: Ryan DeTree#4293

**Comment by ProfElements** [comment]
Water generators need to be waterlogged to generate power. It also needs to be within -64 - 320 in y height. It seems you tried to place a hydro generator at y ~4000 which caused it to error

**Comment by hiphoprexx** [comment]
> Water generators need to be waterlogged to generate power. It also needs to be within -64 - 320 in y height. It seems you tried to place a hydro generator at y ~4000 which caused it to error

Ok and how do I waterlog it ?


> I also do not support stable releases of slimefun. Please use a dev build of slimefun

Switched to latest DEV build 1013

**Comment by ProfElements** [comment]
Just right click the wall with a water bucket to waterlog it
