### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PhoenixCodingStuff** [ProfElements/DynaTech#147]
## Description
There is an error on console on startup

## Steps to reproduce the Issue
Add Slimefun4, Infinity Expansion and Dynatech 

## Expected behavior 
No error

## Server Log / Error Report
https://pastes.dev/WPKHSvmqun

## Environment 
  [Mon 11:16:22 INFO ] This Server uses the following setup of Slimefun:
Paper git-Paper-310 (MC: 1.18.2)
Slimefun DEV - 1014 (git f431aa6d)
Metrics-Module #28
Java 17
Installed Addons: (31)
  GlobalWarming vDEV - 11 (git 73ff77d4)
  SlimeBot vBuild - 6
  Networks vDEV - 34 (git eb71c14d)
  CrystamaeHistoria vDEV - 73 (git 528ad08d)
  AureliumSkills vBeta 1.2.11
  FoxyMachines vDEV - 55 (git c1b69ec7)
  FNAmplifications vDEV - 69 (git 404dcf7e)
  SimpleMaterialGenerators vDEV - 4 (git 5543cc8f)
  DynaTech vDEV - 164 (git beb20ae4)
  SFAdvancements vDEV - 18 (git d1feb028)
  CMILib v1.1.2.5
  InfinityExpansion vDEV - 138 (git fd59b78f)
  ElectricSpawners vDEV - 23 (git 6ec96773)
  MobCapturer vDEV - 17 (git c21b00a5)
  SlimyTreeTaps vDEV - 20 (git 963f0383)
  FlowerPower vDEV - 14 (git 63a37cc0)
  SlimeTinker vDEV - 74 (git 5ae433d4)
  TranscEndence vDEV - 41 (git 98d7d47e)
  FluffyMachines vDEV - 116 (git e439acf9)
  AlchimiaVitae vDEV - 19 (git 24ffb2a5)
  HotbarPets vDEV - 38 (git fa6c871d)
  SlimefunLuckyBlocks vDEV - 36 (git 60f0c8dc)
  ExoticGarden vDEV - 78 (git 7f9a5f63)
  DankTech2 vDEV - 4 (git 803760fb)
  Liquid vDEV - 14 (git 0f5346bf)
  SlimeCustomizer vDEV - 25 (git 4435082d)
  UltimateClaims v1.9.1
  LiteXpansion vDEV - 177 (git 2b65056d)
  ElementManipulation vDEV - 20 (git 2c17c1ce)
  SoulJars vDEV - 23 (git b8358a1f)
  PotionExpansion vDEV - 5 (git e2cfcd8a)

 - Minecraft Version: 1.18.2
 - CS-CoreLib Version: N/A
 - Slimefun Version: Slimefun DEV - 1014 (git f431aa6d)
 - Plugin Version: DynaTech vDEV - 164 (git beb20ae4)

**Comment by ProfElements** [comment]
Its just a warning. This is working as intended
