### ISSUE TITLE
Material Hives Disappearing upon connection with energy network

### ISSUE THREAD

**Issue by samidont0817** [ProfElements/DynaTech#150]
## Description (Required)
When you have an energy network going and you place a material hive within range of the energy network, after a few seconds the hive disappears.

## Steps to reproduce the Issue (Required)
https://www.youtube.com/watch?v=3hIvdWJZmWk

## Expected behavior (Required)
I expected them not to disappear a few seconds after being placed.

## Server Log / Error Report
https://pastebin.com/NRZN5jSG

## Environment (Required)

 - Minecraft Version: git.Purpur-1623
 - CS-CoreLib Version: 
 - Slimefun Version: DEV - 1014
 - Plugin Version: vDEV - 152

**Comment by ProfElements** [comment]
update dynatech
