### ISSUE TITLE
Antigravity Bubble

### ISSUE THREAD

**Issue by Versichert** [ProfElements/DynaTech#152]
Hey, I have problem with antigravity bubble. I placed it connected it to energy. I tried to fly, but i couldn't.  All I can is just a small fly for like 1 sec and then the fly deactivates. So if i want to fly a bit longer I have to double tap space every second to stay above the ground.
I thought it is like unlimited fly while I'm in range of the machine.  

minecraft: Purpur git-Purpur-1632 (MC: 1.18.2)
sf versions: https://pastebin.pl/view/0d312261
CS-CoreLib Version: don't have it

**Comment by ProfElements** [comment]
Fixed by #164
