### ISSUE TITLE
bug after removing the machine

### ISSUE THREAD

**Issue by SrMonsterYT** [ProfElements/DynaTech#160]
I removed the MK2 machine from the 3 worlds, I can't access them yet they keep generating and sending to the chest please fix this, I will have to manually remove each MK2, these MK2 should be very hard to do there are players crafting 64 a day, this no one will use on the server so they should be super hard to do.

information: https://prnt.sc/PgjwKD4LlaKx

**Comment by ProfElements** [comment]
If you don't like the machine then just disable it entirely.

**Comment by SrMonsterYT** [comment]
> If you don't like the machine then just disable it entirely.

has already been removed but there are still people using them
even after removing them they still work unless you go to each one and destroy them manually

**Comment by JasperChaseTOQ** [comment]
that's not a dynatech issue that's an issue with core slimefun and how when a block is disabled ones already placed still work so nothing that can be done on dynatechs end

**Comment by ProfElements** [comment]
As Jasper has says, you have to remove the machines manually. There is nothing I can do
