### ISSUE TITLE
energy regulator

### ISSUE THREAD

**Issue by threlief** [ProfElements/DynaTech#165]
someone places a energy regulator gives error in console and then disappears
put problem in slimefun they said it was a dynatech error when they read report so putting here

## Steps to reproduce the Issue (Required)
get energy regulator
place on ground
it will give error in console
then the regulator will disappear

## Expected behavior (Required)
regulator to stay where placed

## Server Log / Error Report
[](https://pastebin.com/BDf3xD0Q) console error
(https://pastebin.com/PqFGmgsr) in the error folder

## Environment (Required)
Paper git-Paper-135 (MC: 1.19.2)
Slimefun DEV - 1033 (git https://github.com/Slimefun/Slimefun4/commit/5455fb08ecc717e928d075cc2c77768ecb35d349)
Metrics-Module https://github.com/Slimefun/Slimefun4/pull/28
Java 17
Installed Addons: (17)
Networks vDEV - 45 (git ade6fbd0)
DyedBackpacks vDEV - 17 (git 8b329e96)
ExtraTools vDEV - 36 (git 922c0324)
ShopGUIPlus v1.78.0
FoxyMachines vDEV - 59 (git c3ed4f8a)
SlimefunOreChunks vDEV - 15 (git 2520cb23)
DynaTech vDEV - 172 (git 81955fc0)
AdvancedEnchantments v8.15.5
SlimefunLuckyBlocks vDEV - 36 (git 60f0c8dc)
InfinityExpansion vDEV - 140 (git 0098d2fb)
CMILib v1.2.3.6
ElectricSpawners vDEV - 23 (git 6ec96773)
ExtraHeads vDEV - 23 (git 0b59a770)
SoulJars vDEV - 23 (git b8358a1f)
MobCapturer vDEV - 21 (git f82c20fc)
SlimyTreeTaps vDEV - 20 (git 963f0383)
FluffyMachines vDEV - 127 (git cf047dcf)

 - Minecraft Version: 1.19.1 
 - CS-CoreLib Version:
 - Slimefun Version:   Slimefun DEV - 1033
 - Plugin Version:  DynaTech vDEV - 172 (git 81955fc0)

**Comment by threlief** [comment]
well due to the issue had to remove the dynatech plugin members would like it back but cant till problem solved

**Comment by ProfElements** [comment]
I don't see anything in the report that is mine 🤷‍♂️  I dont know how to help

**Comment by ProfElements** [comment]
Can you please confirm this is still an issue?

**Comment by ProfElements** [comment]
Closing as stale
