### ISSUE TITLE
Suggestion: add redstone alloy to material hive

### ISSUE THREAD

**Issue by xX-GATT-Xx** [ProfElements/DynaTech#166]

**Comment by ProfElements** [comment]
Will be done once I get a little bit of time

**Comment by xX-GATT-Xx** [comment]
excellent thank you

**Comment by ProfElements** [comment]
Fixed with [0670ad7](https://github.com/ProfElements/DynaTech/commit/0670ad73402df72ffef339c048e6b93915f15a76)
