### ISSUE TITLE
Exception when right-clicking the Angel Gem

### ISSUE THREAD

**Issue by TheBusyBiscuit** [ProfElements/DynaTech#17]
## Description (Required)

I wanted to look into this addon and the angel gem caught my eye :eyes:
It looks awesome, really good job! Unfortunately the latest update caused an exception to pop up.

## Steps to reproduce the Issue (Required)

1. Unlock the Angel Gem
2. Craft/Cheat an Angel Gem
3. Right Click the Angel Gem

## Expected behavior (Required)

No stacktrace should have appeared.
You perhaps forgot to add the ItemSetting to your SlimefunItem.

## Server Log / Error Report

https://pastebin.com/Zm1LbQpE

## Environment (Required)

 - Minecraft Version: 1.16.4
 - CS-CoreLib Version: *None* 😎 
 - Slimefun Version: Slimefun - DEV 792
 - Plugin Version:  DynaTech - DEV 27

**Comment by ProfElements** [comment]
Thank you for the report 🙇 I did infact forget an ItemSetting. Just pushed.
