### ISSUE TITLE
incorrect info inside mob collector in guide

### ISSUE THREAD

**Issue by xX-GATT-Xx** [ProfElements/DynaTech#170]
## Description (Required)
Mob Collector is showing incorrect data. it says you need an iron sword to get zombie flesh in the guide, but it needs shears instead.

## Steps to reproduce the Issue (Required)
1)get mob collector and sf guide.
2) see what item corresponds to zombie flesh.
3) try it and see it doesnt work. proceed to pull hair for 10min
4)try shears and it works.

## Expected behavior (Required)
i expected the guide to show the correct item
## Environment (Required)

![image](https://user-images.githubusercontent.com/32027056/195952799-8fb181bb-a221-42bd-8407-117527f60a63.png)
![image](https://user-images.githubusercontent.com/32027056/195952827-284ba2f5-3ac9-4704-af77-9c2048bd4afd.png)
![image](https://user-images.githubusercontent.com/32027056/195952849-053dc487-e958-44c9-bddb-c62205c70192.png)

**Comment by ProfElements** [comment]
I think you put this in the wrong addon.
I do not have a mob collector

**Comment by xX-GATT-Xx** [comment]
oops meant supreme my bad
