### ISSUE TITLE
Mineralized Apiary Name

### ISSUE THREAD

**Issue by xMikux** [ProfElements/DynaTech#173]
## Description (Required)
Normal will be ``MaterialName Mineralized Apiary``
![image](https://user-images.githubusercontent.com/26039249/196686815-fd78f170-e770-4d0c-a3ee-1c0c077c9349.png)

but Vanilla MaterialName has ``[]`` inside it
``[MaterialName] Mineralized Apiary``
![image](https://user-images.githubusercontent.com/26039249/196686870-1736da33-c6f1-40b2-ae08-5cbd3fcd88d2.png)

## Steps to reproduce the Issue (Required)
Check Normal Mineralized Apiary and Vanilla material Mineralized Apiary name.

## Expected behavior (Required)
Should not inculde ``[]`` on vanilla item mineralized apiary

## Environment (Required)
![image](https://user-images.githubusercontent.com/26039249/196687058-e46bcc0d-99a4-45b0-94f5-d7ad6be651a7.png)

**Comment by ProfElements** [comment]
This is intended.
