### ISSUE TITLE
Material Hive output Problem

### ISSUE THREAD

**Issue by Voidmaster4051** [ProfElements/DynaTech#175]
When using the Material Hive in dynatech, it used to work where i would put in a stack of a material i wanted, and put in bees to decrease the amount of time it would take and after the given amount of time, it would return a stack of the item. The issue is that now it only gives back 1 item. so for example i have a material hive with a stack of reinforced alloy ingots. and this same hive also has 128 advanced robotic bees. it should give out a new stack of reinforced alloy ingots in 5 minutes but instead only gives 1 ingot. i believe this is an error and that it should be corrected.

Minecraft version 1.19.2
Slimefun version 1034
CS-CoreLib Version was merged with slimefun a long time ago
Dynatech version 180

**Comment by ProfElements** [comment]
Returning 1 item is intended.
