### ISSUE TITLE
Mineralized Apiary  Work Problem

### ISSUE THREAD

**Issue by EnderLight3336** [ProfElements/DynaTech#177]
## Description (Required)

When the  Mineralized Apiary's output is full,it still work,and it consumes energy but not producing item
## Steps to reproduce the Issue (Required)

1.Make output full
2.You'll find it consumes energy but not producing item
## Expected behavior (Required)

When the output is full,the machine should stop working
## Environment (Required)

 - Minecraft Version:1.19.2-R0.1-SNAPSHOT
 - CS-CoreLib Version:NONE
 - Slimefun Version:2022.08-RELEASE
 - Plugin Version: 180(maybe)

**Comment by ProfElements** [comment]
That latest commit should of fixed this <[573f68f](https://github.com/ProfElements/DynaTech/commit/573f68fa7e05449116430ea7719c653e50a09dab)> Please check to confirm and close this issue if it does

**Comment by EnderLight3336** [comment]
I test it,and the problem isn't fixed
![image](https://user-images.githubusercontent.com/95128322/215062851-b7834974-55a9-4d6e-a3da-8f6afa6f4880.png)
![image](https://user-images.githubusercontent.com/95128322/215063036-2f099307-8ad0-4a26-9b2b-0c28851b7a07.png)

**Comment by ProfElements** [comment]
That latest commit should of fixed this. Please check to confirm and close this issue if it does

**Comment by EnderLight3336** [comment]
Now it work well
