### ISSUE TITLE
Picnic Basket Not Triggering Properly

### ISSUE THREAD

**Issue by JustAHuman-xD** [ProfElements/DynaTech#178]
## Description
When using a plugin like Aurelium skills that messes with the hunger system. The picnic basket does not trigger properly or reliably. Instead of feeding the player after they loose enough hunger for the item it does nothing. Or waits until the player is almost out of hunger (regardless of the food)

## Server Log / Error Report
There was nothing in the log

## Environment (Required)
Paper: git-Paper-273 (MC: 1.19.2)

 - Minecraft Version: 1.19.2
 - CS-CoreLib Version: not online
 - Slimefun Version: DEV 1035
 - Plugin Version: DEV 180

![image](https://user-images.githubusercontent.com/65748158/208541751-a25f73fe-0c14-4f59-99e2-d642f70be72f.png)
![image](https://user-images.githubusercontent.com/65748158/208541784-d0a25863-f6b8-4ab7-9547-1bf0accb86f6.png)

**Comment by JustAHuman-xD** [comment]
Something to note is that the Slimefun Cooler does not have the same issue

**Comment by ProfElements** [comment]
Can you please provide a video of this happening? I dont really get what you mean

**Comment by LordIdra** [comment]
Here's a video. The picnic basket in this instance contains baked potatoes (as can be seen at **1:52**)
[https://youtu.be/970fLIqGZbM](https://youtu.be/970fLIqGZbM)
At **0:22** and **4:30**, hunger is restored, but should have been restored earlier, and leaves one hunger bar unfilled.

**Comment by JustAHuman-xD** [comment]
Will do!

**Comment by ProfElements** [comment]
Issue confirmed fixed by: zayan5#8593. Please use the latest build to get the fix.
