### ISSUE TITLE
Growth chambers NPE

### ISSUE THREAD

**Issue by therbz** [ProfElements/DynaTech#181]
## Description (Required)
Any growth chambers being ticked will throw an NPE and are terminated by slimefun for exceeding 4 errors in 4 ticks.
Happens to growth chambers with and without any items in them.

## Steps to reproduce the Issue (Required)
Place a growth chamber.

## Expected behavior (Required)
Growth chambers do not do this.

## Server Log / Error Report
Stacktrace generated
https://pastebin.com/3VRSqge7

## Environment (Required)
Slimefun CYT fork (up-to-date with main SF as of Dec 30 2022)
Paper 1.19.2 b307
DynaTech v184

**Comment by ProfElements** [comment]
The latest commit: [a79a613](https://github.com/ProfElements/DynaTech/commit/a79a613c08b5a4b7cceadbd8fc237f13cc95b3e8) should fix this. Please confirm plz and ty

**Comment by therbz** [comment]
> 

Confirmed to fix
