### ISSUE TITLE
Can't fill up bucket

### ISSUE THREAD

**Issue by xMikux** [ProfElements/DynaTech#182]
## Description (Required)
When install DynaTech on server, normal bucket can't fill up water.

## Steps to reproduce the Issue (Required)
https://user-images.githubusercontent.com/26039249/215283946-1c16c0c2-4929-4bdf-9880-6e5b481cfa09.mp4

## Expected behavior (Required)
Bucket can fill up water.

## Environment (Required)
![image](https://user-images.githubusercontent.com/26039249/215283982-0ec77eb8-2802-4046-b04d-8789e533f771.png)

**Comment by ProfElements** [comment]
The latest commit should fix this! Please confirm :)

**Comment by xMikux** [comment]
Yeah, it's fixed. Thanks!
