### ISSUE TITLE
Antigravity Bubbles Get Terminated After Restart

### ISSUE THREAD

**Issue by TheCyberQuake** [ProfElements/DynaTech#183]
## Description (Required)

Antigravity bubbles work perfectly fine when initially placed, but immediately after server loads up after a restart (before players even get on) DynaTech throws errors and terminates the blocks. After the initial placement, the accept power and grant flight as they describe they should, the problem only happens after the server is stopped and then started again

## Steps to reproduce the Issue (Required)

1. Place the antigravity bubble, allow it to get power (have not tested without power)
2. restart server
3. all antigravity bubbles throw an error, and slimefun terminates them

## Expected behavior (Required)

Antigravity Bubble don't all get terminated by Slimefun after restart, no errors

## Server Log / Error Report

https://pastebin.com/3bEPhGkb
## Environment (Required)

Java Environment:
  Operating System: Linux
  Java Version: 17.0.5

Server Software: Paper
  Build: git-Paper-399 (MC: 1.19.3)
  Minecraft v1.19.3-R0.1-SNAPSHOT

Slimefun Environment:
  Slimefun vDEV - 1043 (git 4bfc4f06)
  Caused by: DynaTech vDEV - 193 (git 616d9713)

Installed Addons (19)
  + ExtraGear DEV - 13 (git c62047e2)
  + SlimeHUD DEV - 8 (git 65155402)
  + InfinityExpansion DEV - 140 (git 0098d2fb)
  + MobCapturer DEV - 26 (git e0f006c2)
  + HotbarPets DEV - 38 (git fa6c871d)
  + Networks DEV - 45 (git ade6fbd0)
  + FoxyMachines DEV - 61 (git 265728f9)
  + DynaTech DEV - 193 (git 616d9713)
  + SimpleMaterialGenerators DEV - 4 (git 5543cc8f)
  + WhatIsThis 5.0
  + PrivateStorage DEV - 18 (git 5832db21)
  + Galactifun DEV - 73 (git d7494214)
  + FluffyMachines DEV - 130 (git 01c839cc)
  + SimpleUtils DEV - 15 (git 4250fd5e)
  + EquivalencyTech ${project.version}
  + SlimeTinker DEV - 77 (git 99a520b9)
  + FNAmplifications DEV - 84 (git dbbefc59)
  + SlimeCustomizer DEV - 29 (git 81552a1b)
  + EMCTech DEV - 3 (git bdc78e46)

**Comment by TheCyberQuake** [comment]
Was asked to test 990c942e4302869fe80cce33c49fa2e458a3af99

New error was generated:
https://pastebin.com/e3Zu5U6Y
I decided to go down the rabbit hole of replacing all of the erroring enabledPlayer.get with the same getOrDefault (multiple happened even after doing it for this second one)
Doing so gets it to a state where the console doesn't error, but no longer will remove players on block break.

I'm not entirely sure how blockstorage works, and my miminal experience with java makes me not fully able to figure out how everything in the antigravity bubble works, but I'm gonna toss an idea out just in case it is "something"
My gut feeling is that while the hashset for enabledPlayers works fine while the server is running, nothing is either saving that hashset or not loading blocks from something like blockstorage into the hashset at startup so that the hashset isn't null at startup. Just a shot in the dark, could be entirely wrong.

**Comment by jefflima1** [comment]
I'm having the same problem reported by a friend.

**Comment by ExtremorGP** [comment]
Same issue for me.

**Comment by FaiqGaming** [comment]
Same issue for me Too Slimefun vDEV 1093 and DynaTech vDEV 194

**Comment by MeowIce** [comment]
It still happen on Dynatech DEV 197.
Logs: https://mclo.gs/GY0lx0a
