### ISSUE TITLE
Portable Liquid Tank become normal water bucket when use on cauldron

### ISSUE THREAD

**Issue by xMikux** [ProfElements/DynaTech#187]
## Description (Required)
When using Portable Liquid Tank on containing water cauldron, it will become normal water bucket.

## Steps to reproduce the Issue (Required)
https://github.com/ProfElements/DynaTech/assets/26039249/75ff9f26-40b0-46c9-988b-caca98ed0fc7

## Expected behavior (Required)
Should not interact on cauldron, or other?

## Environment (Required)
![image](https://github.com/ProfElements/DynaTech/assets/26039249/cc2d0b84-bcb7-4698-9d62-d4e9bad6ae27)

**Comment by ProfElements** [comment]
Fixed with latest
