### ISSUE TITLE
anti gravity bubble keeps terminating after restart.

### ISSUE THREAD

**Issue by MeowIce** [ProfElements/DynaTech#191]
## Description (Required)

Same as #183, the AB keeps terminating itself after booting up, but works perfectly when initially placed.  I thought updating to the latest version (v197) will fix that, but unfortunately...nope. It still happens.
## Steps to reproduce the Issue (Required)

1. Place the Anti gravity bubble.
2. Restart the server
3. When the server booted up, DynaTech throws the error and terminate them.
## Expected behavior (Required)

Antigravity Bubble don't all get terminated by Slimefun after restart, no errors
## Server Log / Error Report

https://mclo.gs/GY0lx0a
## Environment (Required)

Java Environment:
  Operating System: Linux
  Java Version: 18.0.2.1

Server Software: Purpur
  Build: git-Purpur-2035 (MC: 1.20.1)
  Minecraft v1.20.1-R0.1-SNAPSHOT

Slimefun Environment:
  Slimefun vDEV - 1094 (git 7da1af03)
  Caused by: DynaTech vDEV - 197 (git 8fced6ee)

**Comment by ProfElements** [comment]
Fixed by [28e063](https://github.com/ProfElements/DynaTech/commit/b28e063e92e491ae4659b232986010ed8a65baf7)
