### ISSUE TITLE
plugin not working

### ISSUE THREAD

**Issue by 100petr** [ProfElements/DynaTech#195]
## Description (Required)

In slimefun they updated the dough version and dynatech won't start on 1.20.2
## Steps to reproduce the Issue (Required)

Start the server with the latest version of slimefun
## Expected behavior (Required)

The plugin will start
## Server Log / Error Report

https://pastebin.com/hxrvRC34
## Environment (Required)

 - Minecraft Version: 1.20.2
 - CS-CoreLib Version:
 - Slimefun Version: 1104
 - Plugin Version: 201

**Comment by ExtremorGP** [comment]
I have the same problem :/

**Comment by MomaCods** [comment]
Hello I am having the same issue. Its asking if its up to date as well

**Comment by ProfElements** [comment]
The build server im using currently is down. The next build once the build server is up again should be compatible with 1.20.2

**Comment by velshi** [comment]
Just updated to the latest build (DynaTech - #201) and now we're getting this error. Any eta when we can update?

**Comment by womzil** [comment]
I would love to at least have the updated code here on github, so I can build it myself. You could also use github releases temporarily until the issue with slimefun builds server is fixed.

**Comment by ProfElements** [comment]
it is on github rn. you can build it

**Comment by velshi** [comment]
Trying to get it to build with jitpack but it's failing for master
https://jitpack.io/#ProfElements/DynaTech

**Comment by MomaCods** [comment]
Discord said 202 was out but the link takes you back to 201?

**Comment by ProfElements** [comment]
yeah, due to when the build server went offline it never fully built

**Comment by velshi** [comment]
For anyone else, just install IntelliJ Community, and create a new project from VCS/Version Control and enter the repo URL, then learn how to compile with Maven. It's easy and it's just a few button clicks.

**Comment by Techdude404Gaming** [comment]
I have just tried to build it myself but it appears to be giving me the same issues. Is there something I'm missing?
I imported into Visual Studio Code, exported the code to Jar, uploaded to the server, and still gave the error and didn't start.
I am running MC 1.20.2

**Comment by ProfElements** [comment]
I am using 70b8eefd953da23a672e480ca0fee05c582b85c3 and its seems to work just fine on my papermc java server

**Comment by velshi** [comment]
> I have just tried to build it myself but it appears to be giving me the same issues. Is there something I'm missing? I imported into Visual Studio Code, exported the code to Jar, uploaded to the server, and still gave the error and didn't start. I am running MC 1.20.2

Package with Maven. IntelliJ Community Edition makes this super easy. There's a sidebar when you open the project and you'll see options for Maven, then you just select the option to package.

**Comment by ProfElements** [comment]
I have moved over https://blob.build. Please download the most up to date version there: https://blob.build/project/DynaTech/Main
