### ISSUE TITLE
Barbed Wire - iron golem

### ISSUE THREAD

**Issue by 100petr** [ProfElements/DynaTech#196]
## Description (Required)

 Barbed Wire doesn't work on iron golems - it doesn't knock them out
## Steps to reproduce the Issue (Required)

Build bare wire, add electricity
Try mobs like zombie, skeleton. It works for them. Try irongolem - nothing happens
## Expected behavior (Required)

Bare wire will also work on irongolems
## Environment (Required)

![image](https://github.com/ProfElements/DynaTech/assets/29830635/2689d177-f823-4360-b69c-857cf27ff867)

**Comment by ProfElements** [comment]
this is working as intended. only hostile mobs get pushed out of the barbed wire.
