### ISSUE TITLE
When an Anti-Gravity Bubble is broken/not powered flight is not toggled off.

### ISSUE THREAD

**Issue by CheesyOnion** [ProfElements/DynaTech#2]
## Description (Required)
When I place an anti-gravity bubble it gives flight correctly. When I break the block and try to fly I still can fly, even if I was already flying before I broke it.

## Steps to reproduce the Issue (Required)
Break an Anti-Gravity Bubble that was previously powered. You should be able to fly still even though the block is gone. The same thing happens if the block has no power.

## Expected behavior (Required)
Flight should be toggled off if the block has no power or is broken.

## Server Log / Error Report
No errors show up in console after I break the block or cut off its power.

## Environment (Required)
![image](https://user-images.githubusercontent.com/68432025/103357156-7b4f5c80-4a80-11eb-9b58-ae60e2eb9f41.png)
![image](https://user-images.githubusercontent.com/68432025/103357189-915d1d00-4a80-11eb-9d42-5a623cb6bf55.png)

 - Minecraft Version: Paper 1.16.4
 - CS-CoreLib Version: DEV-90
 - Slimefun Version: DEV-769

**Comment by ProfElements** [comment]
The power is only removed when its enabled a player's flight in its area, so that is intended behavior, however having flight when the block is broken is not intended behavior, will push a patch soon :+1:

**Comment by CheesyOnion** [comment]
Sounds good, thanks a bunch!

**Comment by ProfElements** [comment]
Just fixed! It took a minute, sorry for the wait :bow: Thank you for the report!
