### ISSUE TITLE
Plugin is broken on 1.20.2.

### ISSUE THREAD

**Issue by MagmaBro123** [ProfElements/DynaTech#203]
## Description (Required)
Title, please update the plugin.

## Steps to reproduce the Issue (Required)
Use the plugin on a 1.20.2 server.

## Expected behavior (Required)
The plugin to work.

## Server Log / Error Report
https://pastebin.com/BvTDyJb3

## Environment (Required)
![2023-12-13_19 08 28](https://github.com/ProfElements/DynaTech/assets/51277766/28b5d127-3081-4340-8ef7-01a14462eef3)
![2023-12-13_19 08 30](https://github.com/ProfElements/DynaTech/assets/51277766/35748539-e655-4cc7-bda3-0854e7647ab3)

**Comment by ProfElements** [comment]
You are on an old version please update

Download Link: <https://blob.build/project/DynaTech>

**Comment by MagmaBro123** [comment]
I was never tols a new build page existed, besides the old one being broken.

**Comment by ProfElements** [comment]
A reply was here : <https://github.com/ProfElements/DynaTech/issues/195#issuecomment-1849097426>
and recently I announced it on the slimefun addon community discord

Please update, and if the issue persists open a new issue

**Comment by ybw0014** [comment]
You are already told: https://github.com/Slimefun/Slimefun4/issues/4058#issuecomment-1855196435
