### ISSUE TITLE
Error occurred while enabling DynaTech vMain - 17

### ISSUE THREAD

**Issue by seeungeheuer** [ProfElements/DynaTech#207]
## Description (Required)

![error_DynaTech](https://github.com/ProfElements/DynaTech/assets/152896639/b4a5feed-00b4-4e53-9ec3-f634c459fcd5)

 - Minecraft Version: 1.19.2
 - CS-CoreLib Version:
 - Slimefun Version: RC - 36
 - Plugin Version: Main - 17
 - git-Purpur-1858 (MC: 1.19.2)*

**Comment by jefflima1** [comment]
same problem

**Comment by ProfElements** [comment]
I only support the latest version of Minecraft. 1.20.4 at date of writing.
