### ISSUE TITLE
Anti-Gravity Resulting in Permanent Fly When Teleporting

### ISSUE THREAD

**Issue by lati00lati** [ProfElements/DynaTech#208]
## Description (Required)

Teleporting out of an anti-gravity bubbles radius (I personally used a Portable Teleporter) results in permanent creative flight.
Creative flight is also sometimes given when simply leaving the boundaries of the Anti-gravity bubble.

## Steps to reproduce the Issue (Required)

Place an anti-gravity bubble and power it.
Teleport out of the radius, or continuously walk in and out of it until permanent flight is applied.

## Expected behavior (Required)

Regardless of the method for leaving an anti-gravity bubble, flight should be taken away. Additionally, if you go from one Anti-Gravity's bubble to another's, the flight persists and it doesn't deactivate it since you're still in a radius.

## Server Log / Error Report

There are no error logs.

## Environment (Required)

 - Minecraft Version: 1.20.4
 - CS-CoreLib Version: Not Installed
 - Slimefun Version: 1133
 - Plugin Version: Build 18

**Comment by ProfElements** [comment]
Video please. i cant seem to replicate on my test server
