### ISSUE TITLE
Dynatech not working with Slimetinker

### ISSUE THREAD

**Issue by Kirito696** [ProfElements/DynaTech#211]
## Description (Required)
If dynetech is installed Slime tinker would not work, i tried to intall older versions of both plugins still same issue 
tried only these plugins slimefun, dynatech, slimetinker same issue 

## Steps to reproduce the Issue (Required)
Install lates Dynatech with Slimetinker 

## Expected behavior (Required)
They would both work 

## Server Log / Error Report
(https://pastebin.com/NW458nSm)

## Environment (Required)

 - Minecraft Version: 1.20.4
 - CS-CoreLib Version: Version DEV - 92 (git e9150d72)  (tried with  and wihout CS-CoreLi)
 - Slimefun Version: stable build 37  tried with the lates development build as well
 - Plugin Version: DynaTech - build23

**Comment by ProfElements** [comment]
The currently available version of SlimeTinker does not support 1.20.4
