### ISSUE TITLE
Hydro Turbines doesn't generate after installing v33

### ISSUE THREAD

**Issue by RealmKebab** [ProfElements/DynaTech#214]
## Description (Required)
Recently, a friend of mine has a survival slimefun server. He updated it to v(ersion) 33 of DynaTech and all hydro turbines stopped working. This caused the community to basically rage. I've tested this on my own server and it seemed to have stopped turbines from working.
![image](https://github.com/ProfElements/DynaTech/assets/73048123/611d4c59-1d34-4d23-a3ff-ae6378fc0055)

## Steps to reproduce the Issue (Required)
1. Get a Purpur 1.20.4 (2176) server
2. Install Java 21
3. Install Slimefun 4 (Dev 1148)
4. Install DynaTech v33
5. Get Hydro Turbines
6. Place them down
7. They don't generate power

## Expected behavior (Required)
Generating power

## Server Log / Error Report
https://mclo.gs/dSt3Lax

## Environment (Required)
![image](https://github.com/ProfElements/DynaTech/assets/73048123/10b1c50d-af55-4a22-9983-04f48498bb7a)

 - Minecraft Version: 1.20.4
 - CS-CoreLib Version: don't have it
 - Slimefun Version: Dev - 1148
 - Plugin Version: v33

**Comment by ProfElements** [comment]
This is intended behavior. please look for the new water mills in the experimental section
