### ISSUE TITLE
Orechid desappering when place it in the ground

### ISSUE THREAD

**Issue by pump61** [ProfElements/DynaTech#218]
Error Generated: 2024-09-12-22-30

Java Environment:
  Operating System: Linux
  Java Version: 21.0.3

Server Software: Purpur
  Build: git-Purpur-2176 (MC: 1.20.4)
  Minecraft v1.20.4-R0.1-SNAPSHOT

Slimefun Environment:
  Slimefun vRC - 37
  Caused by: DynaTech vMain - 40

Installed Addons (25)
  + Vouchers 1.0.0
  + SlimeHUD DEV - 11 (git b6dc2d53)
  + InfinityExpansion MODIFIED
  + AuraSkills 2.2.3
  + RedProtect 8.1.1-SNAPSHOT
  + SlimeFrame 1.6.2
  + Networks Dev - 3
  + AdvancedEnchantments 9.10.5
  + ShopGUIPlus 1.97.0
  + SimpleMaterialGenerators DEV - 4 (git 5543cc8f)
  + FastMachines Dev - 31
  + MobCapturer DEV - 33 (git 6fc26c35)
  + Supreme MODIFIED
  + ExtraUtilities 1.0.1
  + ExtraGear DEV - 13 (git c62047e2)
  + VillagerTrade Dev - 6
  + SimpleUtils DEV - 15 (git 4250fd5e)
  + FluffyMachines Dev - 8
  + FNAmplifications Dev - 104
  + FlowerPower Dev - 2
  + ExtraTools DEV - 36 (git 922c0324)
  - DynaTech Main - 40
  + WorldEditSlimefun Dev - 7
  + FoxyMachines Dev - 68
  + SlimyTreeTaps DEV - 20 (git 963f0383)

Installed Plugins (121):
  + ViaVersion 5.0.3
  + LuckPerms 5.4.55
  + Vault 1.7.3-b131
  + PlaceholderAPI 2.11.6
  + NextCash 1.2.9
  + LiteBans 2.14.1
  + ClearLag 3.2.2
  + FastAsyncWorldEdit 2.11.1-SNAPSHOT-836;15c6027
  + PlayerPoints 1.0.0
  + Multiverse-Core 4.3.12
  + Essentials 2.21.0-dev+111-b54c8c1
  + nChat 5.6.48
  + Slimefun RC - 37
  + HeadDatabase 4.19.6
  + floodgate 2.2.3-SNAPSHOT (b109-49bd564)
  + ViaBackwards 5.0.3
  + WorldGuard 7.0.9+5934e49
  + ProtocolLib 5.2.0-SNAPSHOT-679
  + DiscordSRV 1.28.1-SNAPSHOT
  + Vouchers 1.0.0
  + DecentHolograms 2.8.11
  - Geyser-Spigot 2.4.2-SNAPSHOT
  + ViaRewind 4.0.2
  + MyPet 3.12
  + SimpleClans 2.19.2-05e7abc
  + SlimeHUD DEV - 11 (git b6dc2d53)
  + InfinityExpansion MODIFIED
  + AuraSkills 2.2.3
  + WorldGuardExtraFlags 4.2.1
  + packetevents 2.5.0+68b7ee51d-SNAPSHOT
  + SilkSpawners 8.0.0
  + PyroLib 1.3.4
  + RedProtect 8.1.1-SNAPSHOT
  + Votifier 2.7.3
  + SlimeFrame 1.6.2
  + Networks Dev - 3
  + AdvancedEnchantments 9.10.5
  + LibsDisguises 10.0.44-SNAPSHOT
  + ShopGUIPlus 1.97.0
  + CMILib 1.5.1.1
  + SimpleMaterialGenerators DEV - 4 (git 5543cc8f)
  + NBTAPI 2.13.1
  + NexEngine 2.2.12
  + PyroFishingPro 4.8.28
  + ChestShop 3.12.3-SNAPSHOT (build 402)
  + ElderGuardianBoss 1.2
  + PinataParty 2.67.0
  + Playtimes 1.4.7
  + FastMachines Dev - 31
  + PhantomSpawnControl 2.1.1
  + MobCapturer DEV - 33 (git 6fc26c35)
  + Supreme MODIFIED
  + HolidayHunt 2.3.7
  + ExtraUtilities 1.0.1
  + ExtraGear DEV - 13 (git c62047e2)
  + DeluxeFireballs 2.2
  + EssentialsSpawn 2.21.0-dev+111-b54c8c1
  + TubeTils 1.0.5
  + Duels 3.5.3
  + LigasVP 1.0.0
  + UltimateAutoRestart 2024.07
  + PlayerWarps 6.30.0
  + VillagerTrade Dev - 6
  + SimpleUtils DEV - 15 (git 4250fd5e)
  + GeyserUpdater 1.6.4
  + UltraRepair 3.0.2
  + BroadcastX 1.5-BETA
  + Hyperstones 1.7.2
  + FluffyMachines Dev - 8
  + Light 1.2
  + PatreonPlugin 1.3
  + HamsterAPI 0.2.4
  + DeathCoordinates 1.12.1
  + Chunky 1.4.10
  + CentralCart 1.0.0-61fb4c
  + PluginManager 2.8.1
  + Coins 1.13.1
  + LushRewards 3.2.0
  + DeluxeMenus 1.14.0-Release
  + TAB 4.1.6
  + ChatReaction 1.8.0
  + Rankup 3.11.3
  + AxMinions 1.0.11
  + MobFarmManager 3.0.0.0
  + EnchantmentDisabler 0.2.3
  + XLTournaments 3.17.3
  + FNAmplifications Dev - 104
  + FlowerPower Dev - 2
  + StreamingDrops 14.1
  + BungeeGuard 1.3-SNAPSHOT
  + GSit 1.10.0
  + ExtraTools DEV - 36 (git 922c0324)
  + DropXP 1.3.1
  - DynaTech Main - 40
  + aEventos 1.5.6
  + RedstoneLimiter 0.0.1
  + BetterRTP 3.6.13
  + nightcore 2.6.2
  + PixelVip 3.1.0
  + AlonsoTags 2.2.1-BETA
  + EZColors 2.2.4
  + Roulette 2.2
  + spark 1.10.43
  + ExcellentCrates 5.0.0
  + Jobs 5.2.4.2
  + CyberLevels 0.5.9
  + AuctionHouse 2.105.0
  + MyCommand 5.7.4
  + MarriageMaster 2.7.7
  + LevelledMobs 4.1.1 b52
  + WardenBoss 0.2
  + TerraformGenerator 16.2.0
  + BlockedCmds 2.1.4
  + WorldEditSlimefun Dev - 7
  + momojs 1.0.3
  + DragonSlayer 0.14.0_Jeppa
  + FoxyMachines Dev - 68
  + AlonsoLeagues 0.9.3-BETA
  + SlimyTreeTaps DEV - 20 (git 963f0383)
  + LoneLibs 1.0.56
  + PlayerVaults 4.0

Block Info:
  World: world
  X: 32
  Y: 218
  Z: 23
  Material: WITHER_ROSE
  Block Data: org.bukkit.craftbukkit.v1_20_R3.block.data.CraftBlockData
  State: org.bukkit.craftbukkit.v1_20_R3.block.CraftBlockState

Ticker-Info:
  Type: Asynchronous

Slimefun Data:
  ID: DYNATECH_ORECHID
  Inventory: false
  Data: {"id":"DYNATECH_ORECHID"}

Stacktrace:

java.lang.NullPointerException: Cannot invoke "me.profelements.dynatech.DynaTech.getTickInterval()" because the return value of "me.profelements.dynatech.DynaTech.getInstance()" is null
	at DynaTech.jar//me.profelements.dynatech.items.electric.machines.Orechid.tick(Orechid.java:59)
	at DynaTech.jar//me.profelements.dynatech.items.abstracts.AbstractTicker$1.tick(AbstractTicker.java:37)
	at Slimefun4-RC.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:184)
	at Slimefun4-RC.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickLocation(TickerTask.java:171)
	at Slimefun4-RC.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickChunk(TickerTask.java:141)
	at Slimefun4-RC.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:110)
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by ProfElements** [comment]
Can you provide more information?

**Comment by pump61** [comment]
the player place the Orechid on the ground and one second the orechid dissapear, i dont have more information

**Comment by ProfElements** [comment]
I'm closing this as there is not enough information since with the exact same version it doesnt happen on my test version.
