### ISSUE TITLE
Console Exception Message Spam

### ISSUE THREAD

**Issue by catter1** [ProfElements/DynaTech#22]
## Description (Required)

I downloaded the latest version of Dyna Tech last night, but now the console is being spammed with these exception messages. I'm not sure what to write here, as there doesn't seem to be anything wrong at first glance from a player's point of view. Please let me know what other information I can provide.

## Steps to reproduce the Issue (Required)

1. Update Slimefun server to 1.16.5
2. Update all add-ons and other plugins
3. Wait overnight
4. Check console to see error message spam

## Expected behavior (Required)

No console spam

## Server Log / Error Report

This gets spammed in the console roughly once a second: https://pastebin.com/TQwaDMix

## Environment (Required)

 - Minecraft Version: 1.16.5 Paper Build 457
 - CS-CoreLib Version: DEV - 92
 - Slimefun Version: vDEV - 805
 - Plugin Version: vDEV - 36

**Comment by ProfElements** [comment]
Closed. Fixed in 43cdee8
