### ISSUE TITLE
DYNATECH_TESSERACT not working properly

### ISSUE THREAD

**Issue by DarrienZ** [ProfElements/DynaTech#220]
## Description (Required)
After updating Dynatech to v38, tesseract stopped working properly. I can't right click the tesseract, and when I use Tesseract Binder to bind the tesseract, the block disappears, and it shows errors in the console. Already updated to latest version still cannot use

## Steps to reproduce the Issue (Required)
https://youtu.be/bV-sMhB_GPQ

## Expected behavior (Required)
-

## Server Log / Error Report
Server Logs: https://pastebin.com/rFs65iaq
Error in SF Folder: https://pastebin.com/63FGH17Y
 
## Environment (Required)
![image-7](https://github.com/user-attachments/assets/0fab38a8-ee54-4033-a54d-09ebcbc192d9)

 - Minecraft Version: git-Paper-497 (MC: 1.20.4)
 - CS-CoreLib Version: - 
 - Slimefun Version: Slimefun version Dev - 1153
 - Plugin Version: DynaTech version Main - 40

**Comment by ProfElements** [comment]
Please use build 41 <https://blob.build/dl/DynaTech/Main/41>
