### ISSUE TITLE
Dimensional Home: always uses same id for all players

### ISSUE THREAD

**Issue by mrcoffee1026** [ProfElements/DynaTech#26]
## Description (Required)
Chunk ID is pre-assigned on the dimensional home item is hardcoded to "chunk id: 4" for every one of these items crafted or "sf give"n to a person.  Every player using this item is taken to the same chunk on the other side.  The return trip does not take them *back* to where they started but instead sends them to the server's initial spawn point for the survival world.

Item is also "used up" and vanishes if used while aiming at the floor.  Working around this now by aiming directly upwards into the air to use the item.

## Steps to reproduce the Issue (Required)
Simply use the item... have any other person attempt to craft/use or just give yourself a new copy of the item and note how the ID is all the same for everyone.
https://prntscr.com/zejgtf

## Expected behavior (Required)
From what I understand, the ID should be different per player so that they get their own little chunk in that world.

## Server Log / Error Report
No relevant logs.

## Environment (Required)
[17:12:57 INFO]: This Server uses the following setup of Slimefun:
Paper git-Paper-466 (MC: 1.16.5)
Slimefun DEV - 818 (git e2f3944d)
Metrics-Module #21
Java 8

Installed Addons: (30)
  GlobalWarming vDEV - 9 (git d21d264b)
  ExtraTools vDEV - 24 (git 791c7468)
  FoxyMachines vDEV - 12 (git 869a3081)
  SlimefunOreChunks vDEV - 12 (git e3700851)
  SensibleToolbox vDEV - 39 (git 9580549f)
  DynaTech vDEV - 37 (git 69a05cdf)
  ExtraGear vDEV - 12 (git 4570ea2c)
  MoreTools vDEV - 9 (git e8cfb32c)
  InfinityExpansion vDEV - 71 (git 224ec368)
  SFCalc vDEV - 15 (git 6586cb3f)
  ElectricSpawners vDEV - 21 (git 8efab150)
  ExtraHeads vDEV - 21 (git a2c68d59)
  MobCapturer vDEV - 15 (git a42c9e0c)
  SlimyTreeTaps vDEV - 17 (git 8f3e755b)
  PrivateStorage vDEV - 16 (git f9468f23)
  TranscEndence vDEV - 22 (git 7660c9f0)
  FluffyMachines vDEV - 64 (git 582f5de7)
  CMI v8.8.1.0
  ChestTerminal vDEV - 42 (git f4aef9ca)
  DyedBackpacks vDEV - 13 (git 964b2d55)
  SoundMuffler vDEV - 19 (git 5caef292)
  SlimefunWarfare vDEV - 13 (git 135cd29e)
  EcoPower vDEV - 3 (git 18ba903d)
  HotbarPets vDEV - 35 (git 99093ddd)
  SlimefunLuckyBlocks vDEV - 31 (git 6fa9afbd)
  ExoticGarden vDEV - 71 (git ef5756d0)
  Liquid vDEV - 10 (git 2277a85b)
  LiteXpansion vDEV - 125 (git 96d1cf20)
  SoulJars vDEV - 21 (git 59212953)

**Comment by ProfElements** [comment]
Update to latest DynaTech version

**Comment by mrcoffee1026** [comment]
Item is still consumed if "used" on the floor.  Using it from the dimensional home sends to the initial spawn of the world instead of the location it was used to send the player there or to the actual spawn point of the world... either would be more appropriate.  It's not giving everyone the same id: there is no id assigned initially and the chunk seems to be assigned based on relative position from 0, 0 where it was used... so all uses from x/z +/- 1000 would all go to chunk id 1, for example, the further away from there you get, the higher the chunk value you get taken to.  Can't say if that's intended or not since it sounded to me like it was assigned "per player" not "per location" but if it's intended to work "per location" then this part is working now.
