### ISSUE TITLE
Dimensional Home item cannot teleport me back to original world

### ISSUE THREAD

**Issue by CactusTheGuy** [ProfElements/DynaTech#27]
## Description (Required)
When i click the dimensional home item in dimensional home world, it can't teleport me back to the original world and split out error in console

## Steps to reproduce the Issue (Required)
1. Use Dimensional Hone item to teleport to the dimensional hone dimension.
2. Wait for a few seconds for everything to load up properly.
3. Use the Dimensional Home item and watch the console.
 You could watch this video instead
 

https://user-images.githubusercontent.com/75614340/108457907-0c36fd00-72a6-11eb-8fca-e15f4087daed.mp4

## Expected behavior (Required)
Clicking the dimensional home item teleport me back to the original world

## Server Log / Error Report
https://pastebin.com/1dhWV3F2

## Environment (Required)
 - Minecraft Version: **Image below**
 - CS-CoreLib Version: *Not installed*
 - Slimefun Version: **Image below**
 - Plugin Version: **Image below**
 
![image](https://user-images.githubusercontent.com/75614340/108457372-1e646b80-72a5-11eb-9e66-9fff91ed5523.png)

**Comment by Fargus5** [comment]
Hi, dimensional home feature doesn't work in the latest dynatech version. The bug has still not been fixed.

**Comment by CactusTheGuy** [comment]
thanks for the reply, you can close this when it got fixed

**Comment by DabbingEevee** [comment]
this issue still occurs

**Comment by CactusTheGuy** [comment]
i need to retest this issue since some of the add-on break on slimefun #820 build

**Comment by ProfElements** [comment]
Im changing how it works rn instead of bed location or the default world spawn im making the player's previous location, if that is null it will teleport you to your bedspawn, if that is null then it will teleport to the default named "world" spawn

**Comment by Fargus5** [comment]
U see? I was right...

**Comment by ProfElements** [comment]
You were having a separate issue unrelated to this one.

**Comment by CactusTheGuy** [comment]
> U see? I was right... 

i think that your server disable the dimensional home :/

**Comment by ProfElements** [comment]
Im currently working through the dimensional home code to figure out where i messed up.

**Comment by ProfElements** [comment]
I think I  fixed it. Currently you have to right click the Dimensional Home item twice to give the correct chunk id though :/
