### ISSUE TITLE
dimensional home

### ISSUE THREAD

**Issue by Fargus5** [ProfElements/DynaTech#28]
hey man, also with all the fix u published the dimensional home still doesn't work.

it send players to only one chunk

**Comment by ProfElements** [comment]
you give me no info to work with. Make a proper bug report.

**Comment by Fargus5** [comment]
@ProfElements I already made a proper report..

U made 2 updates about this problem and it has not been fixed.

Did u try yourself it before to update the build, instead closing the issue?

**Comment by ProfElements** [comment]
I do not see any issues besides this one you have made. You have yet to make a proper report. I did infact test and confirm that you go to different chunks based on the Chunk Id of the item.

**Comment by Fargus5** [comment]
> I do not see any issues besides this one you have made. You have yet to make a proper report. I did infact test and confirm that you go to different chunks based on the Chunk Id of the item.

https://log.mtxserv.com/5kAcTfz#L3104

**Comment by ProfElements** [comment]
That isn't a proper bug report. Please make a new one. This is a separate issue from the other issues I have fixed. Please.

**Comment by Fargus5** [comment]
Listen. forget it, it’s not important. keep the plugin that doesn’t work. someone else will report the error again. after all how many times are you trying to solve it? 5, 7 ? good day
