### ISSUE TITLE
Antigravity bubble vanishes / errors

### ISSUE THREAD

**Issue by mrcoffee1026** [ProfElements/DynaTech#29]
## Description (Required)
Happens after player places item, logs out, then any other player visits location where antigravity bubble is placed: errors thrown in latest.log and error report created.

## Steps to reproduce the Issue (Required)
Place antigravity bubble... and WAIT.  May take several day cycles for some reason (reported 3+).  Player that placed block must leave the world and return to the location while the chunks are unloaded.  

## Expected behavior (Required)
Item should remain placed, errors should not be thrown.

## Server Log / Error Report
latest.log: https://pastebin.com/AKgr2tAH
2021-03-01-13-22.err: https://pastebin.com/cSAJXG2t

## Environment (Required)
[14:17:37 INFO]: This Server uses the following setup of Slimefun:
Paper git-Paper-505 (MC: 1.16.5)
Slimefun DEV - 825 (git 49950cf6)
Metrics-Module #21
Java 8

Installed Addons: (31)
  GlobalWarming vDEV - 9 (git d21d264b)
  ExtraTools vDEV - 25 (git 209f9078)
  FoxyMachines vDEV - 15 (git e62a72b8)
  SlimefunOreChunks vDEV - 13 (git 9f7a2be3)
  SensibleToolbox vDEV - 39 (git 9580549f)
  DynaTech vDEV - 48 (git 044b15b2)
  ExtraGear vDEV - 12 (git 4570ea2c)
  MoreTools vDEV - 10 (git 660e2ce6)
  InfinityExpansion vDEV - 84 (git fb607375)
  SFCalc vDEV - 15 (git 6586cb3f)
  ElectricSpawners vDEV - 22 (git 4cb2c56b)
  ExtraHeads vDEV - 21 (git a2c68d59)
  MobCapturer vDEV - 15 (git a42c9e0c)
  SlimyTreeTaps vDEV - 18 (git ab11a282)
  PrivateStorage vDEV - 16 (git f9468f23)
  TranscEndence vDEV - 23 (git c7ddc06a)
  GeneticChickengineering vDEV - 12 (git 8912d443)
  FluffyMachines vDEV - 67 (git d5ed4a58)
  CMI v8.8.1.5
  ChestTerminal vDEV - 42 (git f4aef9ca)
  DyedBackpacks vDEV - 14 (git 0a051b2b)
  SoundMuffler vDEV - 19 (git 5caef292)
  SlimefunWarfare vDEV - 19 (git 6b17971c)
  EcoPower vDEV - 3 (git 18ba903d)
  HotbarPets vDEV - 36 (git 71e1a5e7)
  SlimefunLuckyBlocks vDEV - 32 (git e108f086)
  ExoticGarden vDEV - 74 (git 3366e8ac)
  Liquid vDEV - 10 (git 2277a85b)
  LiteXpansion vDEV - 125 (git 96d1cf20)
  SoulJars vDEV - 22 (git aded79dd)
  SlimyRepair vDEV - 3 (git c56293bb)

**Comment by ProfElements** [comment]
Forgot to check and remove players if they are in different dimensions then the bubble. Fixed 👍
