### ISSUE TITLE
fly disabling

### ISSUE THREAD

**Issue by 100petr** [ProfElements/DynaTech#3]
## Description (Required)

after drop the item from the inventory the fly will turn off
(the plugin pretends to be non-functional, but it is in the sf guide and it does it for me on the production server where I also have the required exoticgarden)
## Steps to reproduce the Issue (Required)

Turn fly on using essentials (maybe also works with vanilla gamemode creative)
drop the item from the inventory
the fly will turn off
Video: https://youtu.be/ifAPT4dAUA0
## Expected behavior (Required)

fly will not turn off when the item is dropped
## Server Log / Error Report

https://pastebin.com/uN2WnfVS
## Environment (Required)

![image](https://user-images.githubusercontent.com/29830635/103458853-2cb5f280-4d0c-11eb-93d9-fa2b8e82efe0.png)

**Comment by ProfElements** [comment]
Will get working on a fix!

**Comment by ProfElements** [comment]
Fixed it. Forgot to confirm angel gem was source of flight. Thank you for the report :bow:
