### ISSUE TITLE
Healthy Item Band Error

### ISSUE THREAD

**Issue by khronozx** [ProfElements/DynaTech#31]
## Description (Required)

The extra hearts given by the item are reset each time the counter of the Enhanced Health potion effect is reset. Every time it is restarted it wastes saturation so it is just a useless and big waste of food.

## Steps to reproduce the Issue (Required)

![image](https://user-images.githubusercontent.com/55935631/109878153-e3b5e800-7c41-11eb-9259-017d2e41ecf0.png)

The "Improved Health" counter resets from 10 seconds to 14 seconds and the extra life is reset as well:

![image](https://user-images.githubusercontent.com/55935631/109878195-f3cdc780-7c41-11eb-8d66-153d69ab7dc4.png)

## Expected behavior (Required)
 That the extra hearts simply remain stationary and do not restart every few seconds.

## Server Log / Error Report

No, everything is in its latest version and the error happens in several servers with slimefun.

## Environment (Required)
 1.16.5

 
![image](https://user-images.githubusercontent.com/55935631/109879537-b0745880-7c43-11eb-9b80-7a7ffd69be83.png)

Does not have cs-corelib

**Comment by ProfElements** [comment]
Currently there is no way around this. Otherwise people would have access with infinite health boost at one cost once you put on the item or hold it once.

**Comment by sdadad4aq1** [comment]
> Currently there is no way around this. Otherwise people would have access with infinite health boost at one cost once you put on the item or hold it once.

Well, it would be better to eliminate it honestly, by adding this to my armor I have an item that uses up all my hunger thighs in 3 minutes.

**Comment by ProfElements** [comment]
You can remove it from the armor and not use it. Just because one person doesnt like it doesnt mean everyone will.
