### ISSUE TITLE
Lore goes off screen due to it being 1 line

### ISSUE THREAD

**Issue by MagmaBro123** [ProfElements/DynaTech#32]
## Description (Required)
Title.

## Steps to reproduce the Issue (Required)
Hover over an item from this addon, and see that the lore goes off the screen.

## Expected behavior (Required)
The lore being multiple lines and not going off your screen.

## Server Log / Error Report
N/A

## Environment (Required)
![2021-03-04_13 10 51](https://user-images.githubusercontent.com/51277766/110024086-c8e78000-7ce2-11eb-9e23-292753a59fc7.png)
![2021-03-04_13 10 53](https://user-images.githubusercontent.com/51277766/110024095-cb49da00-7ce2-11eb-90c4-434c3ca7aafb.png)

**Comment by ProfElements** [comment]
You dont give me an example of an item of lore that goes off screen.

**Comment by MagmaBro123** [comment]
Oops, sorry.
![2021-03-04_15 27 52](https://user-images.githubusercontent.com/51277766/110039307-e4a85180-7cf5-11eb-98b8-2c1d2a896082.png)

**Comment by ProfElements** [comment]
Thank you 👍

**Comment by MagmaBro123** [comment]
Btw this happen for pretty much all items that have lore that aren't multiple lines
