### ISSUE TITLE
Growth Chamber MK2 makes alot of stuff without regard to a server economy while being incredibly cheap.

### ISSUE THREAD

**Issue by ProfElements** [ProfElements/DynaTech#35]
## Description (Required)

The Growth Chamber MK2 is a giant upgrade for little. 4x the speed and produce.
This can be ridiculous for servers to handle.  Overall I think this block needs to be nerfed.
Maybe adding a config option might work as well.
## Steps to reproduce the Issue (Required)

Put one carrot into the Growth Chamber MK2, get 12 out
???
Profit.
## Expected behavior (Required)

The growth chambers growth rate being much less since how inexpensive it is.
## Server Log / Error Report

Not applicable
## Environment (Required)

Not applicable

**Comment by waleks647** [comment]
Fix: https://github.com/ProfElements/DynaTech/pull/37

**Comment by ProfElements** [comment]
Fixed in 356dc14
