### ISSUE TITLE
Exception: "x not finite"

### ISSUE THREAD

**Issue by hniV** [ProfElements/DynaTech#4]
## Description (Required)

Recently, the console keeps throwing this exception (x not finite).
All information I can provide is the server console, because no players have noticed this.
At the error log, it said something about BarbedWire, I will soon give more details.
If you close this issue, please let me know if I can have chance to re-open this issue or contact you.
I don't know whether this affect gameplay or not, still waiting on detail reports from players.
Thank you in advance.
## Steps to reproduce the Issue (Required)

Working on it.
## Expected behavior (Required)

Console should not throw exception.
Working on it.
## Server Log / Error Report
https://pastebin.com/hM1xPu0G

## Environment (Required)

 - Minecraft Version: Paper v1_16_R2
 - CS-CoreLib Version: vDEV - 92 (git e9150d72)
 - Slimefun Version: vDEV - 774 (git e66af680)
 - Plugin Version: vDEV - 12 (git fc82651c)

**Comment by ProfElements** [comment]
Fixed, forgot to check if they values were finite. Thank you for the bug report :bow:
