### ISSUE TITLE
Flight Gem inventory issues

### ISSUE THREAD

**Issue by VoltroMC** [ProfElements/DynaTech#44]
## Description (Required)

When using a Flight Gem, if I remove it from my inventory and do something like put it in a chest, it doesnt remove my flight ability. I am unsure if this could be due to me being the owner of the server and by default technically having the ability to fly, but it is problematic and can be abused.

(Additionally, it may be beneficial to make a config option or something where the Flight Gem must be in the off-hand to be used, or require more advanced things in the crafting recipe, since atm it can be fairly easy to obtain and is kinda overpowered.)

(And, maybe by shift right-clicking you could manually disable the Flight Gem.)

## Steps to reproduce the Issue (Required)

Get Flight Gem, activate it, put it in chest, and continue flying around.

## Expected behavior (Required)

I expected my flight ability to be disabled when putting the Flight Gem in the chest.

## Server Log / Error Report

There are no errors.

## Environment (Required)

 - Minecraft Version: git-Paper-"60e92c061" (MC: 1.16.5)
 - CS-CoreLib Version: uhm I am not sure. i have it installed but /sf versions doesnt show it anymore
 - Slimefun Version: DEV - 826 (git d33dc965)
 - Plugin Version: vDEV - 69 (git 167758c0)

**Comment by ProfElements** [comment]
Shift Right-Clicking does infact disable the flight gem. Will look into this issue.
