### ISSUE TITLE
Erro flooding on console

### ISSUE THREAD

**Issue by pump61** [ProfElements/DynaTech#45]
13.03 16:50:38 [Server] ERROR Could not pass event EntityDamageEvent to DynaTech vDEV - 76 (git 0f40e330)
13.03 16:50:38 [Server] INFO java.lang.NullPointerException: null
13.03 16:50:38 [Server] INFO at me.profelements.dynatech.listeners.ElectricalStimulatorListener.feedPlayer(ElectricalStimulatorListener.java:49) ~[?:?]
13.03 16:50:38 [Server] INFO at me.profelements.dynatech.listeners.ElectricalStimulatorListener.onHungerDamage(ElectricalStimulatorListener.java:39) ~[?:?]
13.03 16:50:38 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1033.execute(Unknown Source) ~[?:?]
13.03 16:50:38 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:38 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:38 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:38 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:38 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:248) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:38 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1068) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:38 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1050) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:38 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:911) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:38 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1100) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:38 [Server] INFO at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity0(EntityLiving.java:1838) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:38 [Server] INFO at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity0(EntityHuman.java:844) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:38 [Server] INFO at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1166) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:38 [Server] INFO at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:761) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:38 [Server] INFO at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:842) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:38 [Server] INFO at net.minecraft.server.v1_16_R3.FoodMetaData.a(FoodMetaData.java:94) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:38 [Server] INFO at net.minecraft.server.v1_16_R3.EntityHuman.tick(EntityHuman.java:164) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:38 [Server] INFO at net.minecraft.server.v1_16_R3.EntityPlayer.playerTick(EntityPlayer.java:518) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:38 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:178) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:38 [Server] INFO at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:390) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:38 [Server] INFO at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:145) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:38 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1387) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:38 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:379) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:38 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1214) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:38 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1002) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:38 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:38 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
13.03 16:50:43 [Server] ERROR Could not pass event EntityDamageEvent to DynaTech vDEV - 76 (git 0f40e330)
13.03 16:50:43 [Server] INFO java.lang.NullPointerException: null
13.03 16:50:43 [Server] INFO at me.profelements.dynatech.listeners.ElectricalStimulatorListener.feedPlayer(ElectricalStimulatorListener.java:49) ~[?:?]
13.03 16:50:43 [Server] INFO at me.profelements.dynatech.listeners.ElectricalStimulatorListener.onHungerDamage(ElectricalStimulatorListener.java:39) ~[?:?]
13.03 16:50:43 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1033.execute(Unknown Source) ~[?:?]
13.03 16:50:43 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:43 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:43 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:43 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:248) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:43 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1068) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:43 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1050) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:43 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:911) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:43 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1100) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:43 [Server] INFO at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity0(EntityLiving.java:1838) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:43 [Server] INFO at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity0(EntityHuman.java:844) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:43 [Server] INFO at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1166) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:43 [Server] INFO at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:761) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:43 [Server] INFO at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:842) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:43 [Server] INFO at net.minecraft.server.v1_16_R3.FoodMetaData.a(FoodMetaData.java:94) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:43 [Server] INFO at net.minecraft.server.v1_16_R3.EntityHuman.tick(EntityHuman.java:164) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:43 [Server] INFO at net.minecraft.server.v1_16_R3.EntityPlayer.playerTick(EntityPlayer.java:518) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:43 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:178) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:43 [Server] INFO at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:390) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:43 [Server] INFO at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:145) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:43 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1387) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:43 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:379) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:43 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1214) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:43 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1002) ~[patched_1.16.5.jar:git-Paper-526]
13.03 16:50:43 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Paper-526]

 - Minecraft Version: Paper 1.16.5
 - CS-CoreLib Version: Latest Version 92
 - Slimefun Version: 835
 - Plugin Version: DynaTech vDEV - 76

**Comment by ProfElements** [comment]
Update to Latest.

**Comment by ProfElements** [comment]
Invalid, not latest version.
