### ISSUE TITLE
I can't use this plugin

### ISSUE THREAD

**Issue by thebladeofflame** [ProfElements/DynaTech#46]
![image](https://user-images.githubusercontent.com/58851040/111295429-51243880-8686-11eb-9beb-8f278b8eb2d6.png)
![TAAJNPW}V(XZ2064$00(%WA](https://user-images.githubusercontent.com/58851040/111295613-8df02f80-8686-11eb-8fc6-3deb7e569b1e.png)
slimefun: https://github.com/StarWishsama/Slimefun4/releases
I don't know whit should I do

**Comment by ProfElements** [comment]
I dont support forks of slimefun. Please use the original version. <https://github.com/slimefun/slimefun4/>
