### ISSUE TITLE
wireless item output disappears after placing on a chest

### ISSUE THREAD

**Issue by Boomer-1** [ProfElements/DynaTech#49]
Everytime I try to place a wireless item output onto a chest, within 3-4 seconds it disappears.

slimefun dev 854
paper 552
mc 1.16.5
Dynatech v 85

Additional thought on this - it isn't very intuitive on how the power has to work, and not much is offered on the wiki or ingame.

**Comment by Boomer-1** [comment]
[2021-03-27-11-33.zip](https://github.com/ProfElements/DynaTech/files/6216008/2021-03-27-11-33.zip)

**Comment by ProfElements** [comment]
Forgot to check if it inst null before checking agianst the actual object.
