### ISSUE TITLE
Suggestion: Exotic Gardens support for the Growth Chamber

### ISSUE THREAD

**Issue by CheesyOnion** [ProfElements/DynaTech#5]
I think the growth chamber would be an amazing alternative to Advanced Androids for harvesting plants from exotic gardens. It would not only make it more compact to produce items, but certain items like exotic garden tree saplings could be implemented as it is difficult to harvest any of the trees with androids. Also I would appreciate the inclusion of Magical Plants, and maybe it would be fair to make the production rate slower than the rest of the plants for these.

Thanks in advanced!

**Comment by ProfElements** [comment]
Note to self. This also affects the Culinary Generator with ExoticGarden's Custom Foods.
