### ISSUE TITLE
Ghostly Essence can be used to dye sign texts

### ISSUE THREAD

**Issue by andris155** [ProfElements/DynaTech#51]
## Description (Required)

The Ghostly Essence is actually white dye, it can be used to dye sign texts.

## Steps to reproduce the Issue (Required)

1. Give Ghostly Essence.
2. Place sign with text.
3. Right click to sign with Ghostly Essence

## Expected behavior (Required)

Ghostly Essence can't used to dye sign texts.

## Server Log / Error Report

None

## Environment (Required)

Tuinity git-Tuinity-"c303521" (MC: 1.16.5)
Slimefun DEV - 861 (git 73b5ef8b)
Metrics-Module #21
Java 11

Installed Addons: (3)
  InfinityExpansion vDEV - 98 (git 4cf7e322)
  FoxyMachines vDEV - 42 (git ae8d8aba)
  DynaTech vDEV - 88 (git c06f0e25)

**Comment by ProfElements** [comment]
Being able to dye sign text with ghost essence is intended behavior
