### ISSUE TITLE
Picnic Basket automatically consumes then when you are hungry not work

### ISSUE THREAD

**Issue by andris155** [ProfElements/DynaTech#54]
## Description (Required)

Picnic Basket automatically consumes then when you are hungry not work.

## Steps to reproduce the Issue (Required)

1. Place food to the Picnic Basket.
2. Store in inventory.
3. Automatically consumes then when you are hungry not work.

## Expected behavior (Required)

Automatically consumes then when you are hungry if in the inventory.

## Server Log / Error Report

none

## Environment (Required)

Tuinity git-Tuinity-"c303521" (MC: 1.16.5)
Slimefun DEV - 864 (git 82366191)
Metrics-Module #21
Java 11

Installed Addons: (4)
  InfinityExpansion vDEV - 98 (git 4cf7e322)
  SlimefunFix v3.0
  FoxyMachines vDEV - 42 (git ae8d8aba)
  DynaTech vDEV - 88 (git c06f0e25)

**Comment by ProfElements** [comment]
there is little to now information on this. Im going to assume you dont directly konw how the picnic basket works. Its waits until you can get the full value of the food before consuming it. the food in question is usually the last one in the picnic basket

**Comment by andris155** [comment]
https://www.youtube.com/watch?v=0Qiuodw1A10
I don't know how this should work then.

**Comment by ProfElements** [comment]
:eyes: I dont have enough information about this issue from what you have given me. Can you try regenerating your hunger and then use hunger status effect and see if it works then?

**Comment by andris155** [comment]
I checked in the source code.
Picnic Basket feed the player if hunger loss or if hunger cause damage and Picnic Basket in the inventory with stored food.

But real these functions not work. Picnic Basket do nothing if hunger loss or hunger cause damage  and Picnic Basket in the inventory with stored food.

**Comment by ProfElements** [comment]
:shrug: I dont know how to help you in this situation. It works for me and for everyone I have asked about it
