### ISSUE TITLE
Anti Gravity Bubble not enabling fly

### ISSUE THREAD

**Issue by Azakaturan** [ProfElements/DynaTech#56]
## Description (Required)
A player reported the anti gravity bubble wasn't giving fly properly as the lore described.  Instead of giving flight, when I tried it, it kind of gave a second or 2 of fly and then would disable.  If I spam the jump I can glide around.  If I press space once and hold it the second time, I float for a second or so and then fall. I tested it at my base with the same result, and there was enough power to sustain the power draw both times I tried it.  I looked at the code and it looks like it's giving or trying to give the fly permission. 

*Edit- Upon further testing, I believe it has to do with players having temp fly permission.  I tested it our test server without tempfly and it seemed to work fine.

## Steps to reproduce the Issue (Required)
Place Anti Gravity Bubble with power supply and press double jump to fly.  

## Expected behavior (Required)
Flight within the 22.5 radius of the Anti Gravity Bubble.

## Server Log / Error Report
No server log/error in console.

## Environment (Required)
![image](https://user-images.githubusercontent.com/79327162/113078281-a0d72980-9187-11eb-9d89-1f09e59c4216.png)

 - Minecraft Version:
 - CS-CoreLib Version: N/A
 - Slimefun Version: 864
 - Plugin Version: 90

**Comment by ProfElements** [comment]
This isnt an issue on my end its on whatever the tempfly permissions is.
