### ISSUE TITLE
Tesseract doesn't transfer Energy.

### ISSUE THREAD

**Issue by WolterFox** [ProfElements/DynaTech#59]
## Description (Required)
So the Tesseract is a block that sends either items or energy, however (it may be an option that hasn't been turned on), the Tesseract only sends items. Tried everything, overworld to overworld, overworld to end and overworld to the nether. And yet, nothing works! It may be that I got something wrong and if I did, please correct me.

## Steps to reproduce the Issue (Required)
Place a Tesseract somewhere in the world, place yet another in the world, connect the two, no energy travels between each of them.

## Expected behavior (Required)
Well... I expected that energy travels between worlds and two points.

## Server Log / Error Report
I cannot get the Server Log due to me not being the Server's owner :(

## Environment (Required)

 - Minecraft Version: 1.16.5
 - CS-CoreLib Version: sadly I couldn't find it :(
 - Slimefun Version: DEV - 875 (git b4b0636c)
 - Plugin Version: vDEV - 96 (git 2d2d05bd)

**Comment by ProfElements** [comment]
Just placing the tesseracts do not bind them to each other. You need to bind them with the Tesseract Binder
