### ISSUE TITLE
Antigravity bubble stops working when more than 1 is placed

### ISSUE THREAD

**Issue by Kbryst** [ProfElements/DynaTech#62]
## Description (Required)

We've noticed in our testing the antigravity bubble works fine until a second one is placed. 
I had one player on one side of the world place one, it worked fine. A second player (no where near them, but in the same world) placed one in their area and both antigravity bubbles stopped working. One player's flight kept shutting off while the other player couldn't even get up off the ground. Once one player picked their bubble up, the other one started working fine. 

## Steps to reproduce the Issue (Required)

Place two antigravity bubbles down in two different areas. 

## Expected behavior (Required)

They should both be able to fly in their bubble area at the same time.

## Server Log / Error Report

No errors were found.

## Environment (Required)

 - Minecraft Version: 1.16.5, paper 584
 - CS-CoreLib Version: N/A
 - Slimefun Version: Slimefun DEV - 878
 - Plugin Version:  DynaTech vDEV - 99

**Comment by ProfElements** [comment]
Fixed in 9356d17
