### ISSUE TITLE
Rain bug

### ISSUE THREAD

**Issue by ArrozElMank** [ProfElements/DynaTech#63]
## Description (Required)
Hi, I have a problem with the rain, I already deactivated the Weather controller in the world and in the crafting and it still does not rain, when removing its addon it starts to rain normally

## Steps to reproduce the Issue (Required)
https://imgur.com/H539Ehv --->Without dynatech
https://imgur.com/PGxzXw0 ----> With dynatech

## Expected behavior (Required)
Let it Rain

## Server Log / Error Report
Nothing

## Environment (Required)
https://imgur.com/KQNoMwr
 - Minecraft Version: 1.1.6.5
 - CS-CoreLib Version: No
 - Slimefun Version: dev 878
 - Plugin Version: 101

**Comment by ArrozElMank** [comment]
In addition, sometimes the runes of soulbound and foxymachines are fired.

**Comment by ArrozElMank** [comment]
Also the runes of soulbound and foxy fail

**Comment by ProfElements** [comment]
The soulbound runes and foxymachines runes are not mine.
