### ISSUE TITLE
Growth Chambers turn to stained glass upon restart

### ISSUE THREAD

**Issue by CraftyPeach** [ProfElements/DynaTech#65]
## Description (Required)

When placed, the Growth Chamber turns to regular stained glass upon a server restart. This does not seem to affect the plants when the glass is broken and replaced by another chamber. I will note that I was using quartz plants from Exotic Garden.
## Steps to reproduce the Issue (Required)

Place a Growth Chamber, I use the MK 2, then restart the server.
## Expected behavior (Required)

I expect the Chamber to grow the plant and give me the byproduct, in this case, quartz essence, but the Growth Chamber just turns to regular stained glass.
## Environment (Required)

 - Minecraft Version: 1.16.5
 - CS-CoreLib Version:
 - Slimefun Version: DEV-881
 - Plugin Version: vDEV-103

**Comment by CraftyPeach** [comment]
Description: When placed, the Growth Chamber turns to regular stained glass upon a server restart. This does not seem to affect the plants when the glass is broken and replaced by another chamber.
Steps to Reproduce the Issue: Place a Growth Chamber, I use the MK 2, then restart the server.
Expected Behavior: the Growth Chamber will turn to regular stained glass. 
I am using MC Version 1.16.5
Slimefun Version DEV-881
Plugin Version vDEV-103

**Comment by ProfElements** [comment]
There is not enough information. Please give me either a server log or error report.

**Comment by ProfElements** [comment]
Not enough information. Invalid.
