### ISSUE TITLE
Dimensional homes overlap

### ISSUE THREAD

**Issue by Kbryst** [ProfElements/DynaTech#66]
## Description (Required)

So my dimensional home was chunk ID 2, and my admins was chunk ID 4. It seems that other players on creation and use of their dimensional homes have taken over ours. We've been keeping the head block for our dimensional homes in our ender chests. We are OP. The same players also state that their dimensional homes stop working when they log off and they have to get a new one.

## Steps to reproduce the Issue (Required)

Unsure, I guess have an operator claim a dimensional home and throw it in their ender chest. Then have a non operator create and claim one.

## Expected behavior (Required)

Chunk IDS should be different.

## Server Log / Error Report

I didn't find any errors while testing or anything that looked odd in the startup. 
https://pastebin.com/1WRi3Sfv

## Environment (Required)

 - Minecraft Version:
 - CS-CoreLib Version: N/A
 - Slimefun Version: DEV - 881
 - Plugin Version:  DEV - 103

**Comment by ProfElements** [comment]
did this happen in between a server restart? Thinking that chunk ids arent saved across them

**Comment by Kbryst** [comment]
I honestly wouldn't know. We both got our dimensions at least a week ago
and I only noticed today that players were getting the same ones.
