### ISSUE TITLE
Plugin interferes with unbreakable rune and soulbound rune from being applied

### ISSUE THREAD

**Issue by Boomer-1** [ProfElements/DynaTech#67]
## Description (Required)

Variananora was able to confirm somehow Dynatech is preventing the unbreakable and soulbound runes from being applied to tools, weapons and armor.

## Steps to reproduce the Issue (Required)

With Dynatech installed, drop a piece of armor, then drop the soulbound rune, nothing happens.

## Expected behavior (Required)

 Expected the enchantment to get applied.

## Server Log / Error Report

No error logs and nothing in console

## Environment (Required)

 - Minecraft Version: 1.16.5
 - CS-CoreLib Version: na
 - Slimefun Version: 881
 - Plugin Version: 103

**Comment by ProfElements** [comment]
I dont know how to solve this issue at the moment. I dont know what is different from this time and last time.

**Comment by ProfElements** [comment]
Fixed in d5e3a0d2
