### ISSUE TITLE
Electrical stimulator consumes power but didn't restore any hunger

### ISSUE THREAD

**Issue by Overseer9** [ProfElements/DynaTech#69]
## Description (Required)
Electrical stimulator does consumes power when hunger bar decreases
but it did not restore any hunger

## Steps to reproduce the Issue (Required)
- Give poison and hunger effect on yourself (to decrease hunger bar faster)
- wait until hunger bar decreased
- look at your hunger and electrical stimulator power
Video
https://youtu.be/5o5BVwZ4DDY

## Expected behavior (Required)
- electrical stimulator feeds the player when hunger bar decreased

## Server Log / Error Report
No error log

## Environment (Required)
![image](https://user-images.githubusercontent.com/81430883/116296383-bf533380-a7cc-11eb-8812-71d90a15e144.png)

![image](https://user-images.githubusercontent.com/81430883/116296440-d2660380-a7cc-11eb-9355-bca925f2a5e2.png)

**Comment by ProfElements** [comment]
Fixed in 03fca3a
