### ISSUE TITLE
Magical Plants make the growth chamber disappear when used.

### ISSUE THREAD

**Issue by CheesyOnion** [ProfElements/DynaTech#7]
## Description (Required)
Putting a magical plant specifically into a growth chamber causes it to give an error and destroy the growth chamber,

## Steps to reproduce the Issue (Required)
Put any magical plant into a growth chamber and give it power.

## Expected behavior (Required)
It should turn into the magical essence tied to the magical plant you inserted.

## Server Log / Error Report
https://pastebin.com/G159m8Fd

## Environment (Required)
![image](https://user-images.githubusercontent.com/68432025/104110177-fc89c900-52a2-11eb-9be4-64659f51b3cc.png)
![image](https://user-images.githubusercontent.com/68432025/104110168-dbc17380-52a2-11eb-83a5-2b0aaeebb02f.png)

 - Minecraft Version: 1.16.4
 - CS-CoreLib Version: Dev - 90
 - Slimefun Version: Dev - 775
 - Plugin Version: Dev-16

**Comment by Boomer-1** [comment]
for me the magical plants don't do anything. They just sit there. I spoke with the Dev and a new release is out. Try downloading it.

**Comment by Boomer-1** [comment]
ok version 7 is the one with the plants disappearing  profelements
