### ISSUE TITLE
FoodLevelChangeEvent java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by andris155** [ProfElements/DynaTech#72]
## Description (Required)

The food level change cause the java.lang.NullPointerException: null error in the DynaTech.

## Steps to reproduce the Issue (Required)

1. Player food level changed.

## Expected behavior (Required)

The food level change no cause the java.lang.NullPointerException: null error in the DynaTech.

## Server Log / Error Report

https://pastebin.com/7eYfdkLF

## Environment (Required)

[11:31:05 INFO]: This Server uses the following setup of Slimefun:
Tuinity git-Tuinity-"b12d0cc" (MC: 1.16.5)
Slimefun DEV - 890 (git a8e84a7e)
Metrics-Module #21
Java 11

Installed Addons: (14)
  DyedBackpacks vDEV - 14 (git 0a051b2b)
  ExtraTools vDEV - 26 (git 0cb2ad70)
  PomaExpansion v1.3.1
  SlimefunFix v3.0
  FoxyMachines vDEV - 45 (git ce4f8193)
  EcoPower vDEV - 4 (git 2a08d31d)
  DynaTech vDEV - 108 (git f5957369)
  ExtraGear vDEV - 12 (git 4570ea2c)
  SlimefunLuckyBlocks vDEV - 35 (git 3b6586d6)
  InfinityExpansion vDEV - 103 (git 765f00a7)
  RestrictedCreative v2.4.8
  SFCalc vDEV - 20 (git 29ba88c6)
  LiteXpansion vDEV - 146 (git 0064ae01)
  FluffyMachines vDEV - 79 (git 15a0fad9)

**Comment by ProfElements** [comment]
Fixed in 76f4c92
