### ISSUE TITLE
antigravity bubble grants perm flight

### ISSUE THREAD

**Issue by Kbryst** [ProfElements/DynaTech#73]
## Description (Required)

Teleporting out of an antigravity bubble provides permanent flight 

## Steps to reproduce the Issue (Required)

We use CMI to handle teleports, so we walk into the bubble area and then use /back to teleport out. I believe any kind of teleport works.

## Expected behavior (Required)

Flight should have disabled 

## Server Log / Error Report

Unable to find any errors related

## Environment (Required)

Paper git-Paper-629 (MC: 1.16.5)
Slimefun DEV - 890 (git a8e84a7e)
Metrics-Module #21
Java 11

Installed Addons: (19)
  DyedBackpacks vDEV - 14 (git 0a051b2b)
  ExtraTools vDEV - 26 (git 0cb2ad70)
  EcoPower vDEV - 4 (git 2a08d31d)
  DynaTech vDEV - 108 (git f5957369)
  HotbarPets vDEV - 37 (git 63b1553e)
  SlimefunLuckyBlocks vDEV - 35 (git 3b6586d6)
  ExoticGarden vDEV - 76 (git d148a362)
  HeadLimiter v9
  Liquid vDEV - 11 (git bea52454)
  InfinityExpansion vDEV - 103 (git 765f00a7)
  SFCalc vDEV - 20 (git 29ba88c6)
  IllegalStack v2.2.2a
  SlimyTreeTaps vDEV - 18 (git ab11a282)
  PrivateStorage vDEV - 17 (git 43d35d74)
  ColoredEnderChests vDEV - 22 (git 7c92625c)
  GeneticChickengineering v1.2.0
  FluffyMachines vDEV - 79 (git 15a0fad9)
  CMI v8.8.3.6
  ChestTerminal vDEV - 43 (git 3096bab5)

**Comment by ProfElements** [comment]
Its not permanent flight. Its until the player logs off and back in. They get the flight because the Antigravity Bubble has a range it gives/kills flight in otherwise the bubbles would just kill flight outside of that range indiscrimately

**Comment by Kbryst** [comment]
Is it intended?

**Comment by ProfElements** [comment]
:eyes: Excuse me. I will be taking another look at the code

**Comment by Kbryst** [comment]
I'll explain our testing a bit more just incase its needed,

Bungee server, their way of relogging is to move to a different server and back (so like a fast relog), and when they did that it persisted. 

I believe one guy was able to get it to turn off by restarting his client, he was offline for around 10 minutes. I wasn't around for this part of the testing, so I can't confirm it.

**Comment by ProfElements** [comment]
Should be fixed with b199a59. Please reopen this if it still has some weirdness.
