### ISSUE TITLE
[Request] Flight Gem tweak

### ISSUE THREAD

**Issue by Kbryst** [ProfElements/DynaTech#74]
Can we get a config option (or something, anything) that stops the flight gem from being able to change flight speed?

**Comment by Kbryst** [comment]
._. where do I do that?

**Comment by ProfElements** [comment]
items.yml in the slimefun item settings

**Comment by Kbryst** [comment]
Ohhh my bad its the "angel_gem" totally missed that when I looked.

Thanks!
