### ISSUE TITLE
Dragon egg generator not work

### ISSUE THREAD

**Issue by andris155** [ProfElements/DynaTech#76]
## Description (Required)

The Dragon egg generator not work. Generate error report when use.

## Steps to reproduce the Issue (Required)

1. Use dragon egg generator for create energy from the dragon egg.

## Expected behavior (Required)

Dragon egg generator works and no generate error report.

## Server Log / Error Report

https://pastebin.com/x8FXAVu4

## Environment (Required)

[13:35:37 INFO]: This Server uses the following setup of Slimefun:
Tuinity git-Tuinity-"b12d0cc" (MC: 1.16.5)
Slimefun DEV - 898 (git df7b262d)
Metrics-Module #21
Java 11

Installed Addons: (19)
  DyedBackpacks vDEV - 14 (git 0a051b2b)
  ExtraTools vDEV - 26 (git 0cb2ad70)
  PomaExpansion v1.3.1
  FoxyMachines vDEV - 45 (git ce4f8193)
  EcoPower vDEV - 4 (git 2a08d31d)
  HotbarPets vDEV - 37 (git 63b1553e)
  DynaTech vDEV - 109 (git 9a1726aa)
  ExtraGear vDEV - 12 (git 4570ea2c)
  SlimefunLuckyBlocks vDEV - 35 (git 3b6586d6)
  InfinityExpansion vDEV - 103 (git 765f00a7)
  RestrictedCreative v2.4.8
  SFCalc vDEV - 20 (git 29ba88c6)
  LiteXpansion vDEV - 148 (git 26350571)
  SimpleUtils vDEV - 5 (git 8d51c591)
  SlimyTreeTaps vDEV - 18 (git ab11a282)
  MobCapturer vDEV - 15 (git a42c9e0c)
  TranscEndence vDEV - 33 (git e9b4de1a)
  FluffyMachines vDEV - 79 (git 15a0fad9)
  GeneticChickengineering vDEV - 13 (git 37cffcbb)

**Comment by ProfElements** [comment]
Fixed with ea65180
