### ISSUE TITLE
Growth Chamber works without power.

### ISSUE THREAD

**Issue by MagmaBro123** [ProfElements/DynaTech#8]
## Description (Required)
Growth Chamber works without power. Don't really need to say much...

## Steps to reproduce the Issue (Required)
Place a Growth Chamber, and use it without connecting it to any energy network.

## Expected behavior (Required)
The Growth Chamber to not work without power.

## Server Log / Error Report
N/A

## Environment (Required)
![2021-01-10_11 03 36](https://user-images.githubusercontent.com/51277766/104134023-027fb880-533c-11eb-8c60-cb45f57cbb08.png)
![2021-01-10_11 03 38](https://user-images.githubusercontent.com/51277766/104134027-04497c00-533c-11eb-8c5f-b81fb82f2775.png)
(Had to do 2 since MC chat is annoying.)

**Comment by ProfElements** [comment]
This was an underlying issue with all Machines that extended AMachine and didnt overrive tick. Thank you for the bug report 
Fixed in 6483c7e

**Comment by MagmaBro123** [comment]
Thank you.
