### ISSUE TITLE
Don't work with the new version of paper

### ISSUE THREAD

**Issue by Sventt** [ProfElements/DynaTech#83]
Hey dear friend, we have your addon of slimefun, but when we updated to the last version of paper is disable, I hope you can fix that to work with the new version of paper, greetings my friend <3

**Comment by ProfElements** [comment]
This does not tell me anything about what is happening. Please explain more.

**Comment by realonesc** [comment]
I'm having the same problem.
https://pastebin.com/5dypVhgh
Running Paper-715.

**Comment by ProfElements** [comment]
Please fill out a valid bug report form instead of giving me little information to go on. Please resubmit
