### ISSUE TITLE
generator issues lag

### ISSUE THREAD

**Issue by RIPISDRAD** [ProfElements/DynaTech#84]
![2021-04-09_16 17 02](https://user-images.githubusercontent.com/76468672/119263167-31b00b80-bbf3-11eb-9b98-199a81738a96.png)
![2021-04-09_16 17 00](https://user-images.githubusercontent.com/76468672/119263171-34126580-bbf3-11eb-9b5b-edba41801194.png)
yep its like this
and it is the same issues with the end rode things which generates mine stuff like diamonds etc .... they make the server lag i honestly dont know how but these guys can play sf like i never did so everytime they grow way faster and there is no way to stop them! so making the recipe harder is an issue cause they still and will build these (probably gonna test all of ur stuff and report them all if there is an issue)

**Comment by ProfElements** [comment]
This is intended behavior. They are intensive machines. Disable them if your server cant handle them.
