### ISSUE TITLE
 Use of old ItemStackWrapper functions leads  to errors on Slimefun versions before 922.

### ISSUE THREAD

**Issue by winnipeg21** [ProfElements/DynaTech#86]
## Description (Required)
No idea was told to report this

## Server Log / Error Report
https://pastebin.com/0xrMG9Gc

 - Minecraft Version:
 - CS-CoreLib Version: - 
 - Slimefun Version: 925
 - Plugin Version: 120

**Comment by ProfElements** [comment]
I work with the Release Canidate version of slimefun. This will be fixed when the new Slimefun RC comes out.
