### ISSUE TITLE
DynaTech disables on startup (v121)

### ISSUE THREAD

**Issue by Kbryst** [ProfElements/DynaTech#87]
## Description (Required)

As of a few hours ago, DynaTech is now disabling on startup. 

## Server Log / Error Report

https://pastebin.com/rCeSUJ6U

## Environment (Required)

*Was originally on a much older version of paper
Paper git-Paper-755 (MC: 1.16.5)
Slimefun DEV - 930 (git 0224f94e)
Metrics-Module #22
Java 11

Installed Addons: (19)
  DyedBackpacks vDEV - 15 (git 5f5e8b9e)
  ExtraTools vDEV - 28 (git 58488a2e)
  EcoPower vDEV - 4 (git 2a08d31d)
  HotbarPets vDEV - 37 (git 63b1553e)
  DynaTech vDEV - 121 (git ef38d195)
  SlimefunLuckyBlocks vDEV - 35 (git 3b6586d6)
  ExoticGarden vDEV - 76 (git d148a362)
  HeadLimiter v9
  Liquid vDEV - 11 (git bea52454)
  InfinityExpansion vDEV - 114 (git 9d5d3cec)
  SFCalc vDEV - 24 (git 2574e3e0)
  IllegalStack v2.2.2a
  SlimyTreeTaps vDEV - 19 (git 69930ef7)
  PrivateStorage vDEV - 17 (git 43d35d74)
  ColoredEnderChests vDEV - 22 (git 7c92625c)
  GeneticChickengineering v1.2.0
  FluffyMachines vDEV - 83 (git 58b745a4)
  CMI v8.8.4.7
  ChestTerminal vDEV - 43 (git 3096bab5)

**Comment by Kbryst** [comment]
*Rolling back InfinityExpan 1 version did fix it.

**Comment by Azakaturan** [comment]
Same issue as above
