### ISSUE TITLE
Unable to load plugin. Problem with mob data card. 

### ISSUE THREAD

**Issue by Boomer-1** [ProfElements/DynaTech#88]
## Description (Required)

I loaded my server to get this error. In game, the dynatech icon is there, but in machines, nothing is there. the categories exist in the guide.

## Steps to reproduce the Issue (Required)

no idea

## Expected behavior (Required)

plugin to load

## Server Log / Error Report

https://pastebin.com/xasLwwEe

## Environment (Required)

 - Minecraft Version: 1.16.5
 - CS-CoreLib Version: n/a
 - Slimefun Version: dev 933
 - Plugin Version: 120

**Comment by ProfElements** [comment]
Update to latest :)
