### ISSUE TITLE
wither golem multiblock does not spawn the wither

### ISSUE THREAD

**Issue by Boomer-1** [ProfElements/DynaTech#92]
## Description (Required)

build the wither golem multiblock with 2 polished blackstone on the bottom and a pumpkin on top and it does nothing.

## Steps to reproduce the Issue (Required)

build it as it's shown in the guide

## Expected behavior (Required)

according to sf guide, a wither should have spawned

## Server Log / Error Report

no errors

## Environment (Required)

 - Minecraft Version:1.16.5
 - CS-CoreLib Version:
 - Slimefun Version:933
 - Plugin Version: 125

**Comment by Boomer-1** [comment]
Hey Prof, I tried it again today, and it would not spawn on easy or hard mode.

**Comment by ProfElements** [comment]
You sure you are placing the right blocks and clicking the center polished blackstone block?

**Comment by Boomer-1** [comment]
yes. and nothing happens when clicking on any blocks. as a side note, that clicking action is not noted anywhere as a needed step to spawn the wither, but either way it still doesn't spawn

**Comment by Boomer-1** [comment]
I wonder if this is part of the problem. The guide says a pumpkin, but part of the code says carved pumpkin. 
![image](https://user-images.githubusercontent.com/75179680/121819857-07cb9100-cc55-11eb-9c42-f97e5a06d114.png)

I tried a carved pumpkin and it didn't work either

**Comment by ProfElements** [comment]
Did you right click the center polished blackstone?
It does not automatically spawn.

**Comment by ProfElements** [comment]
You need to update. It works on 127.

**Comment by Boomer-1** [comment]
i updated at the time 128 was the most recent, and I couldn't get it to load. it kept throwing errors. I finally got it working in 130.

Thanks!
