### ISSUE TITLE
Error occurred while enabling Dynatech vDev - 126

### ISSUE THREAD

**Issue by GalaxyKat11** [ProfElements/DynaTech#93]
The past few updates for Dynatech have resulted in error messages in console at startup and appears red among list of addons running when command /sf versions is performed. I am providing screenshots of all versions being used currently as well as one of the error message specific to Dynatech.
I am not sure what other info you would need to diagnose or fix, but please ask and I will provide asap.

![bottom](https://user-images.githubusercontent.com/65092397/120941424-b8371380-c6f0-11eb-8f6c-344789098373.png)
![top](https://user-images.githubusercontent.com/65092397/120941428-bb320400-c6f0-11eb-81ca-bba2e60a80d4.png)
![middle](https://user-images.githubusercontent.com/65092397/120941431-bcfbc780-c6f0-11eb-972b-7fa70f731c3f.png)
![Dynatech error](https://user-images.githubusercontent.com/65092397/120941432-be2cf480-c6f0-11eb-953d-3309b4437460.jpg)

**Comment by GalaxyKat11** [comment]
Was this issue closed because it was fixed or because we did not provide enough information? Even after installing release #128 we are getting same error message in console and still shown in red doing /sf versions.

**Comment by ProfElements** [comment]
Closed with being fixed.
