### ISSUE TITLE
groth chamber disapear

### ISSUE THREAD

**Issue by pump61** [ProfElements/DynaTech#99]
## Description (Required)
item disappears if you put oak seedling

## Steps to reproduce the Issue (Required)
https://streamable.com/g06qo8

## Server Log / Error Report
https://pastebin.com/UMQ2mrZD

## Environment (Required)
[22:34:14 INFO]: This Server uses the following setup of Slimefun:
Purpur git-Purpur-1171 (MC: 1.16.5)
Slimefun DEV - 947 (git e58a6219)
Metrics-Module #25
Java 11
Installed Addons: (22)
DyedBackpacks vDEV - 16 (git 20d28ccc)
ExtraTools vDEV - 28 (git 58488a2e)
SlimefunOreChunks vDEV - 13 (git 9f7a2be3)
AlchimiaVitae vDEV - 5 (git 0a8287f0)
EcoPower vDEV - 4 (git 2a08d31d)
DynaTech vDEV - 122 (git ed16c149)
ExtraGear vDEV - 12 (git 4570ea2c)
ExoticGarden vDEV - 76 (git d148a362)
ClayTech vviolet-1.2.24
Liquid vDEV - 12 (git b7a6c543)
CMILib v1.0.2.10
InfinityExpansion vDEV - 114 (git 9d5d3cec)
ElectricSpawners vDEV - 22 (git 4cb2c56b)
LiteXpansion vDEV - 153 (git a9a97232)
SimpleUtils vDEV - 9 (git 7f454341)
SoulJars vDEV - 22 (git aded79dd)
MobCapturer vDEV - 15 (git a42c9e0c)
SlimyTreeTaps vDEV - 19 (git 69930ef7)
SlimeTinker vDEV - 19 (git 069f1f71)
TranscEndence vDEV - 34 (git eece87db)
FluffyMachines vDEV - 85 (git 037a45b8)
ChestTerminal vDEV - 43 (git 3096bab5)

**Comment by ProfElements** [comment]
I need the log from slimefun's error-report folder to do anything about this

**Comment by pump61** [comment]
https://hastebin.com/sanifezoqo.yaml

**Comment by ProfElements** [comment]
Update please. That should fix the issue.
